"""Deterministic mutation-testing harness for the official-schema validator.

WHAT THIS IS
============
A pure-logic library that takes a corpus of official ISAAC records, applies a
catalog of controlled deterministic mutations to **deep clones** of them, runs
the authoritative validator (:func:`isaac_records.official.validate_official`)
and the normalization layer (:func:`isaac_records.diagnostics.diagnose`) over
each clone, and reports whether the observed outcome matched the outcome the
**public vendored schema** predicts.

It answers a question the existing test suite does not: *is ISAAC's validation
behaviour deterministic, side-effect-free, non-guessing and reversible under
controlled perturbation?* — as opposed to *does this one fixture pass?*

WHAT THIS IS NOT
================
* **Database-free.** This module opens no connection, imports no driver, reads
  no credential and knows no hostname. It is driven entirely by records the
  caller hands it. This is a statement about THIS MODULE, not about the
  deployment: ``db_recon.py`` does connect, from the pod. The real-corpus runner
  (the 30 production-derived records in the
  SLAC Postgres) is **BLOCKED** pending Dean's answer to Q19 — see
  ``docs/superpowers/plans/2026-08-02-corpus-validation-authorization.md`` §8.
  Do not add a database caller here; add nothing that could become one.
* **No FastAPI, no route, no network, no filesystem write.** The only file this
  module causes to be read is the vendored schema, and only indirectly, through
  ``isaac_records.official``.
* **Not part of the truth path.** It *consumes* the validator. It never
  reimplements a rule, never decides validity itself, and never writes to
  ``src/`` or ``schema/``. Every expectation it holds is derived by reading
  ``schema/isaac_record_v1.json`` at run time — there is no hand-written list of
  required fields, types or enums anywhere below.
* **No clock, no randomness.** Nothing in any compared or reported value comes
  from ``datetime.now()`` or ``random``. Operator order is a deterministic sort
  on ``operator_id``.

Style precedent: ``apps/api/isaac_api/db_recon.py`` — pure logic, importable,
no FastAPI, fully unit-testable, sanitized output projected through frozen
key allowlists.

MUTATION CATEGORIES IMPLEMENTED
===============================
Every operator below is generated by walking the vendored schema. Letters match
the category taxonomy used in the authorizing plan.

* **A — required-field removal.** One operator per *unconditionally* required
  field (a name in an object subschema's own ``required`` list, reached only by
  descending ``properties``/``items``). Fields required only under
  ``if``/``then``/``else`` are deliberately excluded: their applicability is a
  fact about the record's content, not about the schema (see the "conditional"
  discussion in ``diagnostics.py`` and §4 of the authorization audit).
  Expectation: the record becomes schema-invalid.
* **C — optional-field removal.** One operator per declared property that is
  neither unconditionally nor conditionally required anywhere. Expectation: the
  record stays valid **and** no ``required``-family diagnostic appears that was
  not already in the baseline.
* **D — null / empty / missing distinctions.** ``null``, ``""``, whitespace-only,
  ``[]`` and ``{}`` substituted for a bounded set of required fields (depth ≤ 2,
  no array-item templates). These are **observation-only**: the schema does not
  specify a single answer for every field, so the harness records what the
  engine does rather than asserting a behaviour. ("Absent" is category A.)
* **E — type violations.** The replacement value is chosen deterministically as
  the first candidate in a fixed list whose JSON type is *not* permitted by the
  field's declared ``type``, so string↔number, object↔scalar and scalar↔array
  all fall out of one rule rather than a hand-written table. A second operator
  replaces an array-of-objects with an array holding a scalar element (invalid
  nested structure). Expectation: invalid.
* **F — enum / vocabulary violations.** Two operators per schema ``enum``: an
  obviously-synthetic token, and a **near miss** (the first permitted value with
  its last character removed). The near miss is the one that matters — it is
  what would catch a validator that guessed the intended value or silently
  auto-corrected it. Expectation: invalid, and the mutated value is still the
  token we wrote after validation.
* **G — unknown / additional fields.** An unknown key inserted at the root and
  at every declared object location. The expectation is **read off the schema
  per location**: ``additionalProperties: false`` ⇒ invalid; anything else ⇒
  valid. The vendored v1.05 schema is closed in 37 places and open in ~14, so
  both branches are genuinely exercised.
* **L — multiple simultaneous mutations.** Bounded, representative
  combinations, **not** the full product. The bound is stated at
  :func:`_build_combined_operators`: at most 10 operators — 6 pairs drawn from
  the first four root-level required fields, plus 4 required-removal ×
  enum-violation pairs. Expectation: invalid, with at least two distinct
  diagnostic pointers.

NOT YET IMPLEMENTED, AND WHY
============================
Categories **B, H, I, J and K** are deliberately absent. This is an omission
with a reason, not an oversight:

* **B — conditional-required removal.** Whether an ``if``/``then`` rule fires
  depends on the record's own content, so applicability is record-derived rather
  than schema-derived. Over a real corpus that makes it a field-presence
  disclosure (authorization audit §3–§4). It is implementable safely over public
  fixtures, but building it here would create a runner whose only missing piece
  is the corpus — exactly what §8 says not to build. Deferred with Q19.
* **H — evidence removal** and **I — confirmation removal.** ``evidence`` and
  ``needs_confirmation`` live in the **draft envelope**
  (``src/isaac_records/draft_validator.py``), not in the official record. The
  official schema has no evidence wrapper at all — ``CLAUDE.md`` §4 is explicit
  that official records "avoid custom evidence envelopes". There is nothing to
  remove from an official record, so these categories belong to a draft-level
  harness, not this one. (They are also named as NOT SAFE in the audit §4.)
* **J — provenance mutation.** Provenance in this project lives in the evidence
  **sidecar** (``records/<ULID>.evidence.json``), which the official schema does
  not describe. Same reason as H/I: out of this schema's scope.
* **K — cross-field consistency.** The official schema encodes exactly four
  cross-field rules, all of them ``if``/``then`` — i.e. category B. Anything
  beyond them would be a scientific-consistency judgement, which ``CLAUDE.md``
  §3 confines to the advisory review tier and forbids from asserting validity.
  Implementing K here would mean inventing rules the schema does not state,
  which is a no-guessing violation.

ORACLES
=======
The harness does not merely ask "did the validator throw". Per trial:

``schema_valid``          from :func:`validate_official`, cross-checked against
                          :func:`diagnose` (a disagreement is a reported finding).
``error_count`` / families / schema paths, from :func:`diagnose`.
``source_unchanged``      the input record is byte-identical (canonical JSON)
                          before and after ``apply``, **and** shares no mutable
                          container with the returned clone. This is the single
                          most important oracle: it catches accidental shared
                          state, the failure mode that silently corrupts every
                          later trial.
``restoration``           the declared mutation steps are undone **individually**
                          (not by wholesale replacement), and both the record
                          content and the evaluation must return to baseline. A
                          targeted undo is what makes this failable: an operator
                          whose ``apply`` does something its declared steps do
                          not describe will not restore.
``repeatability``         N identical structured results (N=3 by default).
``ordering_stable``       identical *order*, not merely the same multiset —
                          reported separately from repeatability so an ordering
                          bug is not misfiled as a content bug.
``no_guessing``           the validator populates nothing: a removed path is
                          still absent, a substituted value is still exactly what
                          was written, and the clone is byte-identical before and
                          after validation.
``workflow_consistency``  a narrow invariant on
                          :func:`isaac_api.workflow.derive_workflow`: a
                          schema-invalid record can never reach the ``export``
                          step.

REPORT
======
:func:`build_report` emits **global scalar counts only**, projected key-by-key
through frozen allowlists, mirroring the ``_DB_RECON_*`` pattern in
``routes.py``. There is deliberately no per-operator, per-record or per-path
breakdown: whether a mutation is *applicable* to a record is a fact about that
record's structure, and a per-operator applicability table is a field-presence
map over the corpus (authorization audit §3).

**THIS SHAPE IS NOT YET SAFE FOR THE REAL CORPUS, and an earlier version of this
docstring wrongly said it was "reusable unchanged".** Audit §4 authorizes only
total trials run, ONE global `outcomes_matched` **boolean**, and
`determinism_failures` with a *refusal to elaborate* when nonzero. This module
serves five mutation counts and seven oracle counts, with no refusal path. Over
a 30-row corpus `restoration_failures: 1` is exactly the single-record
structural fact §4.3.1 forbids, and `trials_applicable` is the global sum of the
field-presence map — dominated by the optional-field categories §4 lists as NOT
SAFE.

That is harmless here (10 public fixtures, no route, no caller) and must be
closed BEFORE any corpus is attached, not after. See the "not yet implemented"
section below.
"""

from __future__ import annotations

import copy
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from isaac_records.diagnostics import diagnose, schema_fingerprint
from isaac_records.official import EXPECTED_VERSION, schema_path, validate_official

from .workflow import derive_workflow

__all__ = [
    "ARRAY_ITEM",
    "CATEGORY_COMBINED",
    "CATEGORY_EMPTINESS",
    "CATEGORY_ENUM",
    "CATEGORY_OPTIONAL_REMOVAL",
    "CATEGORY_REQUIRED_REMOVAL",
    "CATEGORY_TYPE",
    "CATEGORY_UNKNOWN_FIELD",
    "EXPECT_INVALID",
    "EXPECT_OBSERVE_ONLY",
    "EXPECT_VALID",
    "Evaluation",
    "HarnessResult",
    "MutationOperator",
    "MutationStep",
    "REPORT_FORMAT_VERSION",
    "ReportKeyError",
    "SchemaModel",
    "TrialOutcome",
    "build_operators",
    "build_failure_report",
    "build_report",
    "check_ordering_stable",
    "check_repeatability",
    "evaluate",
    "introspect_schema",
    "run_harness",
    "run_trial",
]

# --------------------------------------------------------------------------
# Constants
# --------------------------------------------------------------------------

#: Path-template segment standing for "an item of this array". Resolved to
#: index 0 and only index 0 — a bounded, deterministic choice. Sweeping every
#: index would multiply the trial count by record content, which is both slow
#: and (over a real corpus) a per-record disclosure.
ARRAY_ITEM = "*"

CATEGORY_REQUIRED_REMOVAL = "A_required_field_removal"
CATEGORY_OPTIONAL_REMOVAL = "C_optional_field_removal"
CATEGORY_EMPTINESS = "D_null_empty_missing"
CATEGORY_TYPE = "E_type_violation"
CATEGORY_ENUM = "F_enum_violation"
CATEGORY_UNKNOWN_FIELD = "G_unknown_field"
CATEGORY_COMBINED = "L_multiple_simultaneous"

#: The record must become invalid.
EXPECT_INVALID = "record_becomes_schema_invalid"
#: The record must stay valid (and, for category C, gain no `required` error).
EXPECT_VALID = "record_stays_schema_valid"
#: The schema does not specify one answer; the harness records what happened and
#: asserts nothing about validity. Used only by category D.
EXPECT_OBSERVE_ONLY = "outcome_observed_not_asserted"

OP_REMOVE = "remove"
OP_SET = "set"
OP_INSERT_KEY = "insert_key"

# Obviously-synthetic payloads. Every one is a compile-time constant: nothing
# here is derived from a record, so no mutated value can carry record content.
_SYNTHETIC_STRING = "SYNTHETIC_INVALID_TYPE_VALUE_ZZ9"
_SYNTHETIC_NUMBER = -987654321
_SYNTHETIC_ARRAY = ("SYNTHETIC_INVALID_TYPE_ARRAY_ELEMENT_ZZ9",)
_SYNTHETIC_OBJECT_KEY = "synthetic_invalid_type_object_key_zz9"
_SYNTHETIC_ENUM_TOKEN = "SYNTHETIC_INVALID_ENUM_TOKEN_ZZ9"
_SYNTHETIC_UNKNOWN_KEY = "synthetic_unknown_field_zz9"
_SYNTHETIC_NESTED_ITEM = "SYNTHETIC_INVALID_NESTED_ITEM_ZZ9"

#: Ordered candidate replacements for a type violation. The first whose JSON
#: type the field does not permit is used, so the concrete swap (string→number,
#: object→scalar, scalar→array, ...) is derived from the schema rather than
#: enumerated by hand.
_TYPE_CANDIDATES: tuple[tuple[str, Any], ...] = (
    ("string", _SYNTHETIC_STRING),
    ("integer", _SYNTHETIC_NUMBER),
    ("array", list(_SYNTHETIC_ARRAY)),
    ("object", {_SYNTHETIC_OBJECT_KEY: _SYNTHETIC_STRING}),
    ("boolean", True),
)

#: The five emptiness substitutions for category D. "Absent" is category A.
_EMPTINESS_VARIANTS: tuple[tuple[str, Any], ...] = (
    ("null", None),
    ("empty_string", ""),
    ("whitespace_string", "   "),
    ("empty_array", []),
    ("empty_object", {}),
)

#: Category D is bounded to fields at this depth or shallower, with no array
#: template. Five variants per field over the whole schema would dominate the
#: trial count without adding a distinct failure mode.
_EMPTINESS_MAX_DEPTH = 2

#: Combinator/conditional keywords. A `required` list found under any of these
#: (other than inside an `if`, which states a *condition*, not a requirement) is
#: a conditional requirement.
_BRANCH_KEYWORDS = ("allOf", "anyOf", "oneOf")
_APPLY_KEYWORDS = ("then", "else")


class ReportKeyError(KeyError):
    """A report block carried a key that is not on its frozen allowlist.

    Raised on the success path only. Fail-closed has to include the closing:
    the failure envelope projects without raising, because it is what a raise
    degrades *into* — if it raised too, a broken allowlist would escape as an
    unhandled traceback instead of a sanitized envelope. Same reasoning, and the
    same shape, as ``_db_recon_*`` in ``routes.py``.
    """


# --------------------------------------------------------------------------
# Canonical serialization
# --------------------------------------------------------------------------


def canonical(value: Any) -> str:
    """Deterministic JSON rendering used for every byte-identity comparison.

    ``sort_keys=True`` so that a change of key *order* is not reported as a
    change of content; a mutation that only reorders keys is not a mutation of
    the record's meaning.
    """
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _json_type(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):  # bool before int: bool is an int subclass
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    raise TypeError(f"not a JSON value: {type(value).__name__}")


def _type_permitted(json_type: str, declared: Sequence[str]) -> bool:
    """Is ``json_type`` acceptable where ``declared`` types are allowed?

    ``integer`` satisfies a declared ``number`` (JSON Schema's numeric tower);
    the reverse does not hold and is not assumed.
    """
    if json_type in declared:
        return True
    return json_type == "integer" and "number" in declared


def _container_ids(value: Any, out: set[int]) -> None:
    if isinstance(value, dict):
        out.add(id(value))
        for item in value.values():
            _container_ids(item, out)
    elif isinstance(value, list):
        out.add(id(value))
        for item in value:
            _container_ids(item, out)


def shares_container(left: Any, right: Any) -> bool:
    """True if ``left`` and ``right`` share any mutable container by identity.

    A shallow copy passes a naive "the top-level objects differ" check while
    still aliasing every nested dict, so mutating the clone silently mutates the
    source. This catches that before it can corrupt a later trial.
    """
    left_ids: set[int] = set()
    right_ids: set[int] = set()
    _container_ids(left, left_ids)
    _container_ids(right, right_ids)
    return bool(left_ids & right_ids)


def pointer(segments: Sequence[Any]) -> str:
    """Render a path template as a JSON-Pointer-shaped string (``*`` retained)."""
    if not segments:
        return "/"
    return "".join(
        "/" + str(seg).replace("~", "~0").replace("/", "~1") for seg in segments
    )


# --------------------------------------------------------------------------
# Schema introspection — every expectation below is DERIVED, never hardcoded
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class SchemaField:
    """One property declared by the vendored schema, at one location."""

    #: Instance path template, ``*`` for an array item.
    path: tuple[str, ...]
    name: str
    #: In its parent object subschema's own ``required`` list.
    required_unconditionally: bool
    #: Required only under an ``if``/``then``/``else`` (or other combinator).
    required_conditionally: bool
    #: Declared JSON types; empty when the subschema declares none.
    types: tuple[str, ...]
    #: Declared ``enum``, or ``None``.
    enum: tuple[Any, ...] | None
    #: True when this field is an array whose items are objects.
    array_of_objects: bool


@dataclass(frozen=True)
class SchemaObject:
    """One object location declared by the vendored schema."""

    path: tuple[str, ...]
    #: ``additionalProperties: false`` — an unknown key here is a hard failure.
    closed: bool
    declared: tuple[str, ...]


@dataclass(frozen=True)
class SchemaModel:
    fields: tuple[SchemaField, ...]
    objects: tuple[SchemaObject, ...]
    #: Instance paths that some ``then``/``else``/combinator branch requires.
    conditional_required: frozenset[tuple[str, ...]]
    #: Root-level unconditionally required names, in schema declaration order.
    root_required: tuple[str, ...]


def _collect_conditional_required(
    node: Any, path: tuple[str, ...], out: set[tuple[str, ...]]
) -> None:
    """Collect instance paths required by a conditional/combinator branch.

    An ``if`` subschema is deliberately NOT descended: its ``required`` states a
    *condition* for the rule to fire, not a requirement on the record. Treating
    it as a requirement would wrongly move ``context`` out of the optional set
    (v1.05's ``allOf[1].if`` lists it), losing real coverage.
    """
    if not isinstance(node, Mapping):
        return
    for name in node.get("required", ()) or ():
        if isinstance(name, str):
            out.add(path + (name,))
    for prop_name, sub in (node.get("properties") or {}).items():
        _collect_conditional_required(sub, path + (prop_name,), out)
    items = node.get("items")
    if items is not None:
        _collect_conditional_required(items, path + (ARRAY_ITEM,), out)


def _walk_branches(node: Any, path: tuple[str, ...], out: set[tuple[str, ...]]) -> None:
    """Find every conditional branch anywhere in the schema and harvest it."""
    if not isinstance(node, Mapping):
        return
    for keyword in _APPLY_KEYWORDS:
        if keyword in node:
            _collect_conditional_required(node[keyword], path, out)
    for keyword in _BRANCH_KEYWORDS:
        for member in node.get(keyword, ()) or ():
            _walk_branches(member, path, out)
            # A combinator member that is itself a plain schema still states
            # requirements that are not unconditional at `path`.
            _collect_conditional_required(member, path, out)
    for prop_name, sub in (node.get("properties") or {}).items():
        _walk_branches(sub, path + (prop_name,), out)
    items = node.get("items")
    if items is not None:
        _walk_branches(items, path + (ARRAY_ITEM,), out)


def _walk_structure(
    node: Any,
    path: tuple[str, ...],
    conditional: frozenset[tuple[str, ...]],
    fields: list[SchemaField],
    objects: list[SchemaObject],
) -> None:
    """Descend ONLY ``properties``/``items`` — the unconditional structure."""
    if not isinstance(node, Mapping):
        return
    properties = node.get("properties") or {}
    if node.get("type") == "object" or properties:
        objects.append(
            SchemaObject(
                path=path,
                closed=node.get("additionalProperties") is False,
                declared=tuple(properties),
            )
        )
    required = tuple(node.get("required", ()) or ())
    for prop_name, sub in properties.items():
        sub_path = path + (prop_name,)
        declared_type = sub.get("type") if isinstance(sub, Mapping) else None
        if isinstance(declared_type, str):
            types: tuple[str, ...] = (declared_type,)
        elif isinstance(declared_type, list):
            types = tuple(str(t) for t in declared_type)
        else:
            types = ()
        raw_enum = sub.get("enum") if isinstance(sub, Mapping) else None
        items = sub.get("items") if isinstance(sub, Mapping) else None
        fields.append(
            SchemaField(
                path=sub_path,
                name=prop_name,
                required_unconditionally=prop_name in required,
                required_conditionally=sub_path in conditional,
                types=types,
                enum=tuple(raw_enum) if isinstance(raw_enum, list) else None,
                array_of_objects=bool(
                    types == ("array",)
                    and isinstance(items, Mapping)
                    and (items.get("type") == "object" or "properties" in items)
                ),
            )
        )
        _walk_structure(sub, sub_path, conditional, fields, objects)
    items = node.get("items")
    if items is not None:
        _walk_structure(items, path + (ARRAY_ITEM,), conditional, fields, objects)


def introspect_schema(root: Path) -> SchemaModel:
    """Read the vendored schema and derive the mutation model from it.

    The schema document is read through ``isaac_records.official.schema_path``
    so there is exactly one notion of "the authoritative schema" in the process.
    Nothing about required fields, types or enums is written down in this module.
    """
    document = json.loads(schema_path(Path(root)).read_text(encoding="utf-8"))

    conditional: set[tuple[str, ...]] = set()
    _walk_branches(document, (), conditional)

    fields: list[SchemaField] = []
    objects: list[SchemaObject] = []
    _walk_structure(document, (), frozenset(conditional), fields, objects)

    return SchemaModel(
        fields=tuple(fields),
        objects=tuple(objects),
        conditional_required=frozenset(conditional),
        root_required=tuple(document.get("required", ()) or ()),
    )


# --------------------------------------------------------------------------
# Path resolution
# --------------------------------------------------------------------------


def _resolve(template: Sequence[Any], record: Any) -> tuple[tuple[Any, ...], Any] | None:
    """Resolve a path template against a record.

    Returns ``(concrete_path, node)`` or ``None`` when any segment is absent.
    ``*`` resolves to index 0 of a non-empty list; an empty list is unresolvable
    (and therefore the operator is simply not applicable to that record).
    """
    node = record
    concrete: list[Any] = []
    for segment in template:
        if segment == ARRAY_ITEM:
            if not isinstance(node, list) or not node:
                return None
            concrete.append(0)
            node = node[0]
        elif isinstance(node, dict) and segment in node:
            concrete.append(segment)
            node = node[segment]
        else:
            return None
    return tuple(concrete), node


def _node_at(record: Any, concrete: Sequence[Any]) -> Any:
    node = record
    for segment in concrete:
        node = node[segment]
    return node


# --------------------------------------------------------------------------
# Mutation model
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class MutationStep:
    """One elementary edit. Data, not a closure — comparable and printable."""

    op_kind: str
    #: For ``remove``/``set``: the path of the value itself. For ``insert_key``:
    #: the path of the PARENT object.
    path: tuple[str, ...]
    #: ``set``: the replacement value. ``insert_key``: the key name to insert.
    payload: Any = None

    def __post_init__(self) -> None:
        if self.op_kind not in (OP_REMOVE, OP_SET, OP_INSERT_KEY):
            raise ValueError(f"unknown mutation step kind: {self.op_kind!r}")
        if self.op_kind == OP_REMOVE and self.path and self.path[-1] == ARRAY_ITEM:
            # Refused structurally rather than left as a latent trap. `del l[0]`
            # shifts every later element up, so the targeted undo — which writes
            # back by index — would overwrite a sibling instead of re-inserting.
            # No catalog operator does this today; this makes it impossible for
            # one to start.
            raise ValueError(
                "removing an array item is unsupported: the targeted undo "
                "cannot re-insert at an index without shifting siblings"
            )

    def resolve(self, record: Any) -> tuple[Any, ...] | None:
        """Concrete path this step would act on, or ``None`` if inapplicable."""
        if self.op_kind == OP_INSERT_KEY:
            resolved = _resolve(self.path, record)
            if resolved is None:
                return None
            concrete, node = resolved
            if not isinstance(node, dict) or self.payload in node:
                return None
            return concrete
        if self.op_kind in (OP_REMOVE, OP_SET):
            if not self.path:
                return None
            parent = _resolve(self.path[:-1], record)
            if parent is None:
                return None
            parent_concrete, parent_node = parent
            last = self.path[-1]
            if last == ARRAY_ITEM:
                if not isinstance(parent_node, list) or not parent_node:
                    return None
                return parent_concrete + (0,)
            if not isinstance(parent_node, dict) or last not in parent_node:
                return None
            return parent_concrete + (last,)
        raise ValueError(f"unknown mutation step kind: {self.op_kind!r}")


@dataclass(frozen=True)
class MutationOperator:
    """One mutation: what it targets, what it does, what should happen.

    ``apply`` never modifies its argument. Subclasses may override ``apply`` —
    the test suite does exactly that to prove the oracles can fail — but a
    subclass whose behaviour departs from its declared ``steps`` will be caught
    by the restoration oracle, which undoes the declared steps individually.
    """

    operator_id: str
    category: str
    #: JSON-Pointer-shaped target against the PUBLIC schema (``*`` for an item),
    #: or a comma-joined list for a combined operator.
    target: str
    expected_outcome: str
    steps: tuple[MutationStep, ...]
    rationale: str = ""

    def applicability(self, record: Mapping[str, Any]) -> bool:
        """Can this mutation be applied to ``record``?

        Every step must resolve, and no two steps may act on overlapping paths —
        an overlap would make the targeted undo ambiguous.
        """
        resolved: list[tuple[Any, ...]] = []
        for step in self.steps:
            concrete = step.resolve(record)
            if concrete is None:
                return False
            resolved.append(concrete)
        for i, left in enumerate(resolved):
            for right in resolved[i + 1 :]:
                shorter, longer = sorted((left, right), key=len)
                if longer[: len(shorter)] == shorter:
                    return False
        return True

    def apply(self, record: Mapping[str, Any]) -> dict:
        """Return a MUTATED DEEP CLONE. The input is never modified."""
        clone = copy.deepcopy(dict(record))
        for step in self.steps:
            concrete = step.resolve(record)
            if concrete is None:
                raise ValueError(
                    f"operator {self.operator_id!r} is not applicable to this record"
                )
            if step.op_kind == OP_REMOVE:
                del _node_at(clone, concrete[:-1])[concrete[-1]]
            elif step.op_kind == OP_SET:
                _node_at(clone, concrete[:-1])[concrete[-1]] = copy.deepcopy(
                    step.payload
                )
            elif step.op_kind == OP_INSERT_KEY:
                _node_at(clone, concrete)[step.payload] = _SYNTHETIC_STRING
            else:  # pragma: no cover - guarded in MutationStep.resolve
                raise ValueError(f"unknown mutation step kind: {step.op_kind!r}")
        return clone


# --------------------------------------------------------------------------
# Operator catalog construction
# --------------------------------------------------------------------------


def _build_required_removal(model: SchemaModel) -> list[MutationOperator]:
    out: list[MutationOperator] = []
    for entry in model.fields:
        if not entry.required_unconditionally:
            continue
        target = pointer(entry.path)
        out.append(
            MutationOperator(
                operator_id=f"remove_required_field@{target}",
                category=CATEGORY_REQUIRED_REMOVAL,
                target=target,
                expected_outcome=EXPECT_INVALID,
                steps=(MutationStep(OP_REMOVE, entry.path),),
                rationale="unconditionally required by the vendored schema",
            )
        )
    return out


def _build_optional_removal(model: SchemaModel) -> list[MutationOperator]:
    out: list[MutationOperator] = []
    for entry in model.fields:
        if entry.required_unconditionally or entry.required_conditionally:
            continue
        target = pointer(entry.path)
        out.append(
            MutationOperator(
                operator_id=f"remove_optional_field@{target}",
                category=CATEGORY_OPTIONAL_REMOVAL,
                target=target,
                expected_outcome=EXPECT_VALID,
                steps=(MutationStep(OP_REMOVE, entry.path),),
                rationale="declared but required by no schema branch",
            )
        )
    return out


def _build_emptiness(model: SchemaModel) -> list[MutationOperator]:
    out: list[MutationOperator] = []
    for entry in model.fields:
        if not entry.required_unconditionally:
            continue
        if len(entry.path) > _EMPTINESS_MAX_DEPTH or ARRAY_ITEM in entry.path:
            continue
        target = pointer(entry.path)
        for label, value in _EMPTINESS_VARIANTS:
            out.append(
                MutationOperator(
                    operator_id=f"set_{label}@{target}",
                    category=CATEGORY_EMPTINESS,
                    target=target,
                    expected_outcome=EXPECT_OBSERVE_ONLY,
                    steps=(MutationStep(OP_SET, entry.path, copy.deepcopy(value)),),
                    rationale=(
                        "absent / null / empty are distinct states the schema "
                        "does not resolve uniformly; behaviour is observed"
                    ),
                )
            )
    return out


def _build_type_violation(model: SchemaModel) -> list[MutationOperator]:
    out: list[MutationOperator] = []
    for entry in model.fields:
        target = pointer(entry.path)
        if entry.types:
            replacement: Any = None
            found = False
            for json_type, candidate in _TYPE_CANDIDATES:
                if not _type_permitted(json_type, entry.types):
                    replacement = copy.deepcopy(candidate)
                    found = True
                    break
            if found:
                out.append(
                    MutationOperator(
                        operator_id=f"violate_type@{target}",
                        category=CATEGORY_TYPE,
                        target=target,
                        expected_outcome=EXPECT_INVALID,
                        steps=(MutationStep(OP_SET, entry.path, replacement),),
                        rationale=(
                            "replacement JSON type is outside the declared "
                            f"type(s) {','.join(entry.types)}"
                        ),
                    )
                )
        if entry.array_of_objects:
            out.append(
                MutationOperator(
                    operator_id=f"violate_nested_structure@{target}",
                    category=CATEGORY_TYPE,
                    target=target,
                    expected_outcome=EXPECT_INVALID,
                    steps=(
                        MutationStep(OP_SET, entry.path, [_SYNTHETIC_NESTED_ITEM]),
                    ),
                    rationale="array of objects given a scalar element",
                )
            )
    return out


def _build_enum_violation(model: SchemaModel) -> list[MutationOperator]:
    out: list[MutationOperator] = []
    for entry in model.fields:
        if not entry.enum:
            continue
        target = pointer(entry.path)
        out.append(
            MutationOperator(
                operator_id=f"violate_enum@{target}",
                category=CATEGORY_ENUM,
                target=target,
                expected_outcome=EXPECT_INVALID,
                steps=(MutationStep(OP_SET, entry.path, _SYNTHETIC_ENUM_TOKEN),),
                rationale="token outside the schema's declared vocabulary",
            )
        )
        # The near miss is the operator that matters: a validator that guessed
        # the intended term, or auto-corrected it, would pass the obvious case
        # and fail here.
        first = entry.enum[0]
        if isinstance(first, str) and len(first) > 1:
            near = first[:-1]
            if near and near not in entry.enum:
                out.append(
                    MutationOperator(
                        operator_id=f"violate_enum_near_miss@{target}",
                        category=CATEGORY_ENUM,
                        target=target,
                        expected_outcome=EXPECT_INVALID,
                        steps=(MutationStep(OP_SET, entry.path, near),),
                        rationale=(
                            "one character short of a permitted term; must be "
                            "rejected, never corrected to the nearest match"
                        ),
                    )
                )
    return out


def _build_unknown_field(model: SchemaModel) -> list[MutationOperator]:
    out: list[MutationOperator] = []
    for location in model.objects:
        target = pointer(location.path)
        out.append(
            MutationOperator(
                operator_id=f"add_unknown_field@{target}",
                category=CATEGORY_UNKNOWN_FIELD,
                target=target,
                # Read off the schema per location, not assumed globally.
                expected_outcome=EXPECT_INVALID if location.closed else EXPECT_VALID,
                steps=(
                    MutationStep(OP_INSERT_KEY, location.path, _SYNTHETIC_UNKNOWN_KEY),
                ),
                rationale=(
                    "additionalProperties is false here"
                    if location.closed
                    else "this location is open by design"
                ),
            )
        )
    return out


#: Bound for category L. At most 6 + 4 = 10 operators are generated: pairs drawn
#: from the first four root-level required fields (C(4,2) = 6) and four
#: required-removal × enum-violation pairs. The full product of the ~700
#: single-step operators is deliberately NOT explored: combination coverage adds
#: no new failure mode here, only runtime.
_COMBINED_REQUIRED_HEAD = 4
_COMBINED_ENUM_PAIRS = 4


def _build_combined_operators(model: SchemaModel) -> list[MutationOperator]:
    root_required = [
        entry
        for entry in model.fields
        if entry.required_unconditionally and len(entry.path) == 1
    ][:_COMBINED_REQUIRED_HEAD]
    enum_fields = [entry for entry in model.fields if entry.enum][
        : _COMBINED_ENUM_PAIRS + _COMBINED_REQUIRED_HEAD
    ]

    out: list[MutationOperator] = []
    for i, left in enumerate(root_required):
        for right in root_required[i + 1 :]:
            target = f"{pointer(left.path)},{pointer(right.path)}"
            out.append(
                MutationOperator(
                    operator_id=f"remove_two_required_fields@{target}",
                    category=CATEGORY_COMBINED,
                    target=target,
                    expected_outcome=EXPECT_INVALID,
                    steps=(
                        MutationStep(OP_REMOVE, left.path),
                        MutationStep(OP_REMOVE, right.path),
                    ),
                    rationale="two simultaneous required-field removals",
                )
            )

    paired = 0
    for entry in enum_fields:
        if paired >= _COMBINED_ENUM_PAIRS:
            break
        # Pick a required field that does not overlap the enum target.
        partner = next(
            (
                candidate
                for candidate in root_required
                if candidate.path != entry.path[: len(candidate.path)]
            ),
            None,
        )
        if partner is None:
            continue
        target = f"{pointer(partner.path)},{pointer(entry.path)}"
        out.append(
            MutationOperator(
                operator_id=f"remove_required_and_violate_enum@{target}",
                category=CATEGORY_COMBINED,
                target=target,
                expected_outcome=EXPECT_INVALID,
                steps=(
                    MutationStep(OP_REMOVE, partner.path),
                    MutationStep(OP_SET, entry.path, _SYNTHETIC_ENUM_TOKEN),
                ),
                rationale="a required-field removal plus a vocabulary violation",
            )
        )
        paired += 1
    return out


def build_operators(root: Path) -> tuple[MutationOperator, ...]:
    """Build the full deterministic operator catalog from the vendored schema.

    Sorted by ``operator_id`` so the trial order never depends on dict
    iteration, schema key order, or anything else that could drift.
    """
    model = introspect_schema(root)
    operators: list[MutationOperator] = []
    operators += _build_required_removal(model)
    operators += _build_optional_removal(model)
    operators += _build_emptiness(model)
    operators += _build_type_violation(model)
    operators += _build_enum_violation(model)
    operators += _build_unknown_field(model)
    operators += _build_combined_operators(model)

    seen: set[str] = set()
    unique: list[MutationOperator] = []
    for operator in sorted(operators, key=lambda op: op.operator_id):
        if operator.operator_id in seen:
            continue
        seen.add(operator.operator_id)
        unique.append(operator)
    return tuple(unique)


# --------------------------------------------------------------------------
# Evaluation and oracles
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Evaluation:
    """One structured validation result, comparable for equality and order."""

    schema_valid: bool
    error_count: int
    rule_families: tuple[str, ...]
    schema_paths: tuple[str, ...]
    #: Ordered per-diagnostic identity. Order is significant.
    signature: tuple[tuple[str, str, str, str, bool], ...]
    #: True when `validate_official` and `diagnose` disagree about validity.
    engines_disagree: bool

    @property
    def unordered(self) -> frozenset[tuple[str, str, str, str, bool]]:
        return frozenset(self.signature)


def evaluate(record: Mapping[str, Any], root: Path) -> Evaluation:
    """Run BOTH engines over ``record`` and structure the result.

    ``validate_official`` decides ``schema_valid`` (it is the authority);
    ``diagnose`` supplies the machine-comparable detail. They are cross-checked
    rather than assumed to agree — a disagreement between two views of the same
    schema is exactly the kind of defect this harness exists to surface.
    """
    official = validate_official(dict(record), Path(root))
    report = diagnose(dict(record), Path(root))
    signature = tuple(
        (d.pointer, d.rule_family, d.kind, d.message, d.conditional)
        for d in report.diagnostics
    )
    return Evaluation(
        schema_valid=official.ok,
        error_count=len(report.diagnostics),
        rule_families=tuple(sorted({d.rule_family for d in report.diagnostics})),
        schema_paths=tuple(sorted({d.schema_pointer for d in report.diagnostics})),
        signature=signature,
        engines_disagree=official.ok != report.ok,
    )


def check_repeatability(evaluations: Sequence[Evaluation]) -> bool:
    """True when every run produced the same *set* of diagnostics.

    Deliberately unordered: an ordering difference is reported by
    :func:`check_ordering_stable` instead, so an ordering bug is never misfiled
    as a content bug.
    """
    if not evaluations:
        return False
    first = evaluations[0]
    return all(
        item.schema_valid == first.schema_valid
        and item.error_count == first.error_count
        and item.rule_families == first.rule_families
        and item.schema_paths == first.schema_paths
        and item.unordered == first.unordered
        for item in evaluations
    )


def check_ordering_stable(evaluations: Sequence[Evaluation]) -> bool:
    """True when every run produced the diagnostics in the same ORDER."""
    if not evaluations:
        return False
    first = evaluations[0].signature
    return all(item.signature == first for item in evaluations)


def _required_pointers(evaluation: Evaluation) -> frozenset[str]:
    return frozenset(
        item[0] for item in evaluation.signature if item[1] == "required"
    )


def _workflow_consistent(schema_valid: bool) -> bool:
    """A schema-invalid record must never reach the ``export`` step.

    Narrow on purpose. ``derive_workflow`` is a pure function of its arguments,
    so this asserts the one property that connects validation truth to the
    workflow the UI shows: an invalid record cannot present ``export`` as the
    current step, and cannot show ``export`` as completed.

    **THIS IS NOT A PER-TRIAL ORACLE, and the report's counter name overstates
    it.** It takes a single boolean and calls a pure function; it never sees the
    record, the mutation, or the clone. Over N trials it can therefore only be
    all-zero or all-N — it is a ``derive_workflow`` regression check evaluated
    once per trial, not an independent per-trial observation like
    ``source_unchanged`` or ``restoration``. It is retained because the property
    it checks is worth pinning, and named here so nobody reads
    ``workflow_consistency_failures: 0`` as 3111 independent confirmations.
    """
    derived = derive_workflow(
        pending_count=0,
        draft_ok=schema_valid,
        ready=schema_valid,
        exported=False,
        rev=1,
    )
    steps = {step["id"]: step for step in derived["ordered_steps"]}
    if steps["export"]["state"] == "completed":
        return False
    if schema_valid:
        return derived["current_step"] == "export"
    return derived["current_step"] not in (None, "export")


# --------------------------------------------------------------------------
# Trials
# --------------------------------------------------------------------------

#: Oracle failure labels. Stable strings so a caller can group without parsing.
ORACLE_SOURCE_MUTATED = "source_mutated"
ORACLE_RESTORATION = "restoration"
ORACLE_REPEATABILITY = "repeatability"
ORACLE_ORDERING = "ordering_instability"
ORACLE_NO_GUESSING = "no_guessing"
ORACLE_WORKFLOW = "workflow_consistency"
ORACLE_ENGINE_DISAGREEMENT = "engine_disagreement"


@dataclass(frozen=True)
class TrialOutcome:
    """The full result of applying one operator to one record.

    Rich by design — this is the *internal* structure. It is NEVER projected
    into :func:`build_report`, which carries global scalars only.
    """

    operator_id: str
    category: str
    expected_outcome: str
    applicable: bool
    observed_valid: bool | None = None
    observed_error_count: int | None = None
    outcome_matched: bool | None = None
    oracle_failures: tuple[str, ...] = ()
    #: For category D: what the engine actually did, for reporting to a human.
    observation: str | None = None


def run_trial(
    record: Mapping[str, Any],
    operator: MutationOperator,
    root: Path,
    *,
    baseline: Evaluation | None = None,
    repeat: int = 3,
) -> TrialOutcome:
    """Apply one operator to one record and run every oracle.

    ``record`` is never modified; that is itself one of the oracles.
    """
    if repeat < 1:
        raise ValueError("repeat must be at least 1")

    if not operator.applicability(record):
        return TrialOutcome(
            operator_id=operator.operator_id,
            category=operator.category,
            expected_outcome=operator.expected_outcome,
            applicable=False,
        )

    # Snapshot BEFORE the lazy baseline, not after. Review finding: taking
    # `before` after `evaluate` means that on the `baseline=None` path — the
    # public default, exercised by several tests — a validator that mutated its
    # input would pollute `record` first, and both `source_unchanged` and
    # `no_guessing` would compare against the already-polluted state and go
    # blind. `run_harness` precomputes the baseline so the sweep was never
    # affected; the direct-call path was.
    before = canonical(record)

    if baseline is None:
        baseline = evaluate(record, root)
    originals = [
        (step, step.resolve(record), copy.deepcopy(_original_value(record, step)))
        for step in operator.steps
    ]

    clone = operator.apply(record)
    after = canonical(record)

    failures: list[str] = []
    if before != after or shares_container(record, clone):
        failures.append(ORACLE_SOURCE_MUTATED)

    clone_before_validation = canonical(clone)
    evaluations = [evaluate(clone, root) for _ in range(repeat)]
    if canonical(clone) != clone_before_validation:
        failures.append(ORACLE_NO_GUESSING)

    observed = evaluations[0]
    if not check_repeatability(evaluations):
        failures.append(ORACLE_REPEATABILITY)
    if not check_ordering_stable(evaluations):
        failures.append(ORACLE_ORDERING)
    if any(item.engines_disagree for item in evaluations):
        failures.append(ORACLE_ENGINE_DISAGREEMENT)

    # no_guessing: the validator populated nothing and corrected nothing.
    for step, concrete, _original in originals:
        if concrete is None:  # pragma: no cover - applicability already checked
            continue
        if step.op_kind == OP_REMOVE:
            if _resolve(step.path, clone) is not None:
                failures.append(ORACLE_NO_GUESSING)
        elif step.op_kind == OP_SET:
            resolved = _resolve(step.path, clone)
            if resolved is None or canonical(resolved[1]) != canonical(step.payload):
                failures.append(ORACLE_NO_GUESSING)
        elif step.op_kind == OP_INSERT_KEY:
            node = _node_at(clone, concrete)
            if not isinstance(node, dict) or step.payload not in node:
                failures.append(ORACLE_NO_GUESSING)

    # restoration: undo the DECLARED steps individually, in reverse order, in
    # the same clone that was just validated. Individually is what makes this
    # oracle failable: a wholesale `clone = deepcopy(record)` would restore any
    # clone whatsoever, including one that `apply` had damaged beyond its
    # declared steps. Re-validating afterwards is not redundant with the content
    # comparison: `official.load_official_validator` reads through an
    # `lru_cache`, so "the same bytes still evaluate to the baseline result" is
    # a claim about engine state, not only about the record.
    for step, concrete, original in reversed(originals):
        if concrete is None:  # pragma: no cover - applicability already checked
            continue
        if step.op_kind in (OP_REMOVE, OP_SET):
            _node_at(clone, concrete[:-1])[concrete[-1]] = copy.deepcopy(original)
        elif step.op_kind == OP_INSERT_KEY:
            node = _node_at(clone, concrete)
            if isinstance(node, dict):
                node.pop(step.payload, None)
    if canonical(clone) != before or evaluate(clone, root) != baseline:
        failures.append(ORACLE_RESTORATION)

    if not _workflow_consistent(observed.schema_valid):
        failures.append(ORACLE_WORKFLOW)

    matched: bool | None
    observation: str | None = None
    if operator.expected_outcome == EXPECT_INVALID:
        matched = not observed.schema_valid
        if matched and operator.category == CATEGORY_COMBINED:
            matched = len({item[0] for item in observed.signature}) >= 2
    elif operator.expected_outcome == EXPECT_VALID:
        matched = observed.schema_valid
        if operator.category == CATEGORY_OPTIONAL_REMOVAL:
            new_required = _required_pointers(observed) - _required_pointers(baseline)
            matched = matched and not new_required
    else:
        matched = None
        observation = "valid" if observed.schema_valid else "invalid"

    return TrialOutcome(
        operator_id=operator.operator_id,
        category=operator.category,
        expected_outcome=operator.expected_outcome,
        applicable=True,
        observed_valid=observed.schema_valid,
        observed_error_count=observed.error_count,
        outcome_matched=matched,
        oracle_failures=tuple(dict.fromkeys(failures)),
        observation=observation,
    )


def _original_value(record: Mapping[str, Any], step: MutationStep) -> Any:
    """The value a step will overwrite/remove (``None`` for ``insert_key``)."""
    if step.op_kind == OP_INSERT_KEY:
        return None
    resolved = _resolve(step.path, record)
    return None if resolved is None else resolved[1]


# --------------------------------------------------------------------------
# Harness
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class HarnessResult:
    """Internal, rich result. See :func:`build_report` for what may be served."""

    records_scanned: int
    records_passing_baseline: int
    records_failing_baseline: int
    operators_defined: int
    trials: tuple[TrialOutcome, ...] = ()
    schema_fingerprint: str = ""

    @property
    def applicable_trials(self) -> tuple[TrialOutcome, ...]:
        return tuple(t for t in self.trials if t.applicable)

    def oracle_failures(self, label: str) -> tuple[TrialOutcome, ...]:
        return tuple(t for t in self.trials if label in t.oracle_failures)

    @property
    def unexpected(self) -> tuple[TrialOutcome, ...]:
        return tuple(t for t in self.trials if t.outcome_matched is False)


def run_harness(
    records: Iterable[Mapping[str, Any]],
    root: Path,
    *,
    operators: Sequence[MutationOperator] | None = None,
    repeat: int = 3,
) -> HarnessResult:
    """Run every operator against every record.

    ``records`` is supplied by the caller: this module deliberately knows no
    corpus location, so it cannot grow a database or fixture dependency by
    accident.
    """
    root = Path(root)
    catalog = tuple(operators) if operators is not None else build_operators(root)
    corpus = [dict(record) for record in records]

    passing = 0
    trials: list[TrialOutcome] = []
    for record in corpus:
        baseline = evaluate(record, root)
        if baseline.schema_valid:
            passing += 1
        for operator in catalog:
            # Per-trial fail-closed. A pathological operator that raises would
            # otherwise abort the whole sweep and produce NO report at all --
            # fail-closed was designed (see `build_failure_report`) but not
            # wired, which review proved by making an operator raise `KeyError`
            # straight out of `run_trial`. A raising operator is now recorded as
            # one unexpected outcome and the sweep continues; the exception is
            # NOT stored, because its text could carry a record value.
            try:
                trials.append(
                    run_trial(record, operator, root, baseline=baseline, repeat=repeat)
                )
            except (KeyboardInterrupt, SystemExit):
                raise
            except BaseException:  # noqa: BLE001 - must never leak, must never abort
                trials.append(
                    TrialOutcome(
                        operator_id=operator.operator_id,
                        category=operator.category,
                        expected_outcome=operator.expected_outcome,
                        applicable=True,
                        outcome_matched=False,
                    )
                )

    return HarnessResult(
        records_scanned=len(corpus),
        records_passing_baseline=passing,
        records_failing_baseline=len(corpus) - passing,
        operators_defined=len(catalog),
        trials=tuple(trials),
        schema_fingerprint=schema_fingerprint(root),
    )


# --------------------------------------------------------------------------
# Sanitized aggregate report
# --------------------------------------------------------------------------

REPORT_FORMAT_VERSION = 1

#: FROZEN top-level key allowlist. Every response — ok or failure — carries
#: exactly these keys and nothing else.
_REPORT_KEYS: tuple[str, ...] = (
    "status",
    "report_format_version",
    "schema_version",
    "schema_fingerprint",
    "corpus",
    "mutations",
    "oracles",
    "limitations",
)

#: FROZEN `corpus` allowlist. Three global scalars. Nothing keyed by record.
_CORPUS_KEYS: tuple[str, ...] = (
    "records_scanned",
    "records_passing_baseline",
    "records_failing_baseline",
)

#: FROZEN `mutations` allowlist. Global scalars only — no per-operator,
#: per-category or per-path breakdown. That omission is the whole point:
#: "operator X applied to 12 of 30 records" discloses that 12 records populate
#: X, which is a field-presence map over the corpus (authorization audit §3).
_MUTATION_KEYS: tuple[str, ...] = (
    "operators_defined",
    "trials_attempted",
    "trials_applicable",
    "trials_skipped_not_applicable",
    "expected_outcome_matches",
    "unexpected_outcomes",
    "observation_only_trials",
)

#: FROZEN `oracles` allowlist. Each is a count of trials that failed that
#: oracle. Every one should be 0; a nonzero value is a defect in ISAAC, not in
#: the corpus, and warrants a synthetic minimal reproducer.
_ORACLE_KEYS: tuple[str, ...] = (
    "source_mutation_failures",
    "restoration_failures",
    "repeatability_failures",
    "ordering_instability_failures",
    "no_guessing_failures",
    "workflow_consistency_failures",
    "engine_disagreements",
)

#: What these numbers cannot establish. Fixed constants — nothing interpolated,
#: so this adds no leak surface.
LIMITATIONS: tuple[str, ...] = (
    # Scoped to THIS MODULE on purpose. It must not read as a claim about what
    # the deployment as a whole touches — `apps/api/isaac_api/db_recon.py` does
    # connect, from the pod, and `CLAUDE.md` §15 is explicit that the honest
    # form is "no connection was opened here", never "the database has never
    # been contacted". `test_backend_copy_truthfulness.py` enforces the shape.
    "This module opens no connection to any database and imports no driver; the "
    "corpus is supplied by the caller and, in this repository, is the public "
    "upstream example set.",
    "Counts are global scalars. Per-operator, per-category and per-record "
    "applicability breakdowns are deliberately absent: mutation applicability is "
    "a fact about a record's structure, so a breakdown is a field-presence map.",
    "Zero oracle failures is evidence over the corpus actually run, not a proof "
    "over all records or all mutations.",
    "Category D (null / empty / missing) outcomes are observed, not asserted: "
    "the vendored schema does not resolve those states uniformly for every field.",
    "Mutation categories B, H, I, J and K are not implemented; see the module "
    "docstring for the reason each is out of scope.",
)


def _project(
    built: Mapping[str, Any], allowlist: Sequence[str], *, strict: bool
) -> dict:
    """Project ``built`` onto ``allowlist``, key by key.

    An unlisted key can never be served, in either mode. On the success path an
    unlisted (or missing) key additionally raises, failing closed. The failure
    envelope does NOT raise: it is what a raise degrades into, and if it raised
    too a broken allowlist would escape as an unhandled traceback instead of a
    sanitized envelope.
    """
    if strict:
        extra = sorted(set(built) - set(allowlist))
        if extra:
            raise ReportKeyError(f"key not on the frozen allowlist: {extra[0]!r}")
        missing = sorted(set(allowlist) - set(built))
        if missing:
            raise ReportKeyError(f"required key missing from block: {missing[0]!r}")
        return {key: built[key] for key in allowlist}
    return {key: built.get(key) for key in allowlist}


def build_report(result: HarnessResult) -> dict:
    """Project a :class:`HarnessResult` onto the sanitized aggregate contract."""
    trials = result.trials
    applicable = [t for t in trials if t.applicable]

    corpus = _project(
        {
            "records_scanned": result.records_scanned,
            "records_passing_baseline": result.records_passing_baseline,
            "records_failing_baseline": result.records_failing_baseline,
        },
        _CORPUS_KEYS,
        strict=True,
    )
    mutations = _project(
        {
            "operators_defined": result.operators_defined,
            "trials_attempted": len(trials),
            "trials_applicable": len(applicable),
            "trials_skipped_not_applicable": len(trials) - len(applicable),
            "expected_outcome_matches": sum(
                1 for t in applicable if t.outcome_matched is True
            ),
            "unexpected_outcomes": sum(
                1 for t in applicable if t.outcome_matched is False
            ),
            "observation_only_trials": sum(
                1 for t in applicable if t.outcome_matched is None
            ),
        },
        _MUTATION_KEYS,
        strict=True,
    )
    oracles = _project(
        {
            "source_mutation_failures": len(result.oracle_failures(ORACLE_SOURCE_MUTATED)),
            "restoration_failures": len(result.oracle_failures(ORACLE_RESTORATION)),
            "repeatability_failures": len(result.oracle_failures(ORACLE_REPEATABILITY)),
            "ordering_instability_failures": len(result.oracle_failures(ORACLE_ORDERING)),
            "no_guessing_failures": len(result.oracle_failures(ORACLE_NO_GUESSING)),
            "workflow_consistency_failures": len(result.oracle_failures(ORACLE_WORKFLOW)),
            "engine_disagreements": len(
                result.oracle_failures(ORACLE_ENGINE_DISAGREEMENT)
            ),
        },
        _ORACLE_KEYS,
        strict=True,
    )

    return _project(
        {
            "status": "ok",
            "report_format_version": REPORT_FORMAT_VERSION,
            "schema_version": EXPECTED_VERSION,
            "schema_fingerprint": result.schema_fingerprint,
            "corpus": corpus,
            "mutations": mutations,
            "oracles": oracles,
            "limitations": list(LIMITATIONS),
        },
        _REPORT_KEYS,
        strict=True,
    )


#: Every status :func:`build_failure_report` may emit. A frozen allowlist, not a
#: convention: an earlier version echoed its ``status`` argument verbatim on the
#: reasoning that "callers must pass a constant". Nothing enforced that, and the
#: natural database-backed caller is ``except Exception as exc:
#: build_failure_report(str(exc))`` — which would put a connection string, a
#: host, or a record id straight into the served envelope. That is precisely the
#: leak the rest of this module is engineered to prevent, so the contract is now
#: mechanical rather than documentary.
FAILURE_STATUSES: tuple[str, ...] = ("error", "unavailable", "refused")


def build_failure_report(status: str) -> dict:
    """Sanitized envelope for a run that produced no result.

    ``status`` MUST be a member of :data:`FAILURE_STATUSES`; anything else is
    replaced by ``"error"`` rather than echoed. No exception text, no argument,
    and nothing derived from a record can reach the response through this path.
    Every other field is null. Projected non-strictly, for the reason given in
    :func:`_project`.
    """
    safe_status = status if status in FAILURE_STATUSES else "error"
    return _project(
        {
            "status": safe_status,
            "report_format_version": REPORT_FORMAT_VERSION,
            "schema_version": EXPECTED_VERSION,
            "limitations": list(LIMITATIONS),
        },
        _REPORT_KEYS,
        strict=False,
    )
