/*
 * Fixtures for the EXPERIMENT-SCOPED graph.
 *
 * Every value here is unmistakably synthetic: `2099` dates, `SYNTH` ids, an
 * `example.invalid`-grade vocabulary, and a formula (`CuO2`) that is already the
 * repository's standing synthetic sample. NOTHING in this file is derived from a
 * real experiment, a real person, a real beamline session, or the
 * production-derived record table. The stress fixture is generated by a loop, so
 * it cannot accidentally carry real content at all.
 */
import type {
  ApiArtifactsResponse,
  ApiDraftGroup,
  ApiEvidenceClassification,
  ApiEvidenceEntry,
  ApiExperimentDetail,
  ApiValidateResult,
  ApiWarningsResponse,
  ExperimentGraphBundle,
} from '../lib/types';
import { fixtureWorkflow } from './apiFixtures';

export const GRAPH_EXP_ID = '01SYNTHGRAPHEXP00000000000';
export const GRAPH_RECORD_ID = '01SYNTHGRAPHRECORD00000000';
export const GRAPH_LINK_TARGET = '01SYNTHGRAPHLINKED00000000';

const VERSION = { rev: 2, updated_utc: '2099-05-01T10:00:00Z', version: '1.0' };

export function graphDetail(
  overrides: Partial<ApiExperimentDetail> = {},
): ApiExperimentDetail {
  return {
    id: GRAPH_EXP_ID,
    title: 'Synthetic XANES — CuO (Cu K-edge) graph fixture',
    status: 'needs_attention',
    created_utc: '2099-05-01T09:00:00Z',
    pending_count: 1,
    evidenced_field_count: 3,
    exported: false,
    record_id: null,
    ...VERSION,
    draft_ok: true,
    artifact_refs: { record_filename: null, sidecar_filename: null },
    source_files: ['mock_campaign.csv', 'raw_scan_listing.txt'],
    workflow: fixtureWorkflow({
      pending_count: 1,
      draft_ok: true,
      ready: false,
      exported: false,
      rev: VERSION.rev,
    }),
    artifact: { state: 'none', reason: null },
    ...overrides,
  } as ApiExperimentDetail;
}

export const graphGroups: ApiDraftGroup[] = [
  {
    title: 'System & Instrument',
    fields: [
      {
        path: 'system.technique',
        label: 'Technique',
        value: 'HERFD-XAS',
        status: 'verified',
        evidence_count: 1,
        source_types: ['spreadsheet'],
      },
    ],
  },
  {
    title: 'Sample',
    fields: [
      {
        path: 'sample.material.formula',
        label: 'Formula',
        value: 'CuO2',
        status: 'verified',
        evidence_count: 1,
        source_types: ['spreadsheet'],
      },
    ],
  },
];

export const graphEvidence: ApiEvidenceEntry[] = [
  {
    path: 'system.technique',
    value: 'HERFD-XAS',
    status: 'verified',
    evidence: [
      {
        source_type: 'spreadsheet',
        source_file: 'mock_campaign.csv',
        locator: "Sheet 'Campaign Info', field=technique",
        quote: 'HERFD-XAS',
      },
    ],
  },
  {
    path: 'sample.material.formula',
    value: 'CuO2',
    status: 'verified',
    evidence: [
      {
        source_type: 'spreadsheet',
        source_file: 'mock_campaign.csv',
        locator: "Sheet 'Sample', field=formula",
        quote: 'CuO2',
      },
    ],
  },
  {
    path: 'implicit:absorbing_element',
    value: 'Cu',
    status: 'inferred',
    evidence: [
      {
        source_type: 'derivation',
        rule: 'absorbing element = sole non-oxygen element in sample.material.formula',
      },
    ],
  },
  {
    path: 'assets:processing_notebook',
    value: 'c3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b345',
    status: 'verified',
    evidence: [
      {
        source_type: 'file_listing',
        source_file: 'raw_scan_listing.txt',
        locator: 'line 16, ssrl-archive://BL15-2/2099_run_000/notebooks/',
        quote: 'xanes_reduction_v2.ipynb',
      },
      {
        source_type: 'user_confirmation',
        question: 'What is the sha256 of the processing notebook?',
        answer: 'c3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b345',
        timestamp: '2099-05-01T09:30:00Z',
      },
    ],
  },
];

export const graphValidateDryRun: ApiValidateResult = {
  ok: false,
  errors: [
    { path: '$.measurement.series', message: 'series is a required property' },
    { path: '$.sample.material.formula', message: "'CuO2' is not of type 'object'" },
  ],
  schema: 'ISAAC v1.05',
  dry_run: true,
};

export const graphWarnings: ApiWarningsResponse = {
  advisory: true,
  gating: false,
  warnings: [{ code: 'NO_LINKS', where: 'record.links', message: 'no relationships declared' }],
  dry_run: true,
};

export const graphClassification: ApiEvidenceClassification = {
  record_rev: 0,
  field_results: [
    {
      field: 'system.technique',
      classification: 'supported',
      value_state: 'confirmed',
      explanation: 'Backed by observed evidence.',
      sources: [{ source_type: 'spreadsheet', locator: "Sheet 'Campaign Info', field=technique" }],
    },
    {
      field: 'implicit:absorbing_element',
      classification: 'inferred_candidate',
      value_state: 'candidate',
      explanation: 'Proposed by a derivation rule; unconfirmed — not entered as fact.',
      sources: [{ source_type: 'derivation' }],
    },
  ],
  counts: {
    supported: 1,
    inferred_candidate: 1,
    insufficient_evidence: 0,
    conflicting_evidence: 0,
    unknown: 0,
    unreadable: 0,
  },
};

export const graphArtifactsNull: ApiArtifactsResponse = {
  record: null,
  sidecar: null,
  record_filename: null,
  sidecar_filename: null,
  artifact: { state: 'none', reason: null },
};

/** A synthetic exported record: two channels, one independent variable, one
 *  asset joined by natural key, one contributor, and ONE declared link. */
export const graphExportedRecord: Record<string, unknown> = {
  isaac_record_version: '1.05',
  record_id: GRAPH_RECORD_ID,
  record_type: 'evidence',
  record_domain: 'characterization',
  measurement: {
    series: [
      {
        series_id: 'averaged_spectrum',
        independent_variables: [{ name: 'incident_energy', unit: 'eV', values: [8970, 8975] }],
        channels: [
          { name: 'absorption', unit: 'mu_normalized', role: 'primary_signal', values: [0.02, 0.03] },
          { name: 'i0_monitor', unit: 'counts', role: 'auxiliary_signal', values: [50000, 50100] },
        ],
      },
    ],
    qc: { status: 'valid' },
  },
  assets: [
    {
      asset_id: 'processing_notebook',
      content_role: 'processing_script',
      media_type: 'application/x-ipynb+json',
    },
  ],
  descriptors: {
    outputs: [
      {
        label: 'synthetic_review_2099',
        descriptors: [{ name: 'xanes_inflection_point_energy', unit: 'eV', source: 'manual' }],
      },
    ],
  },
  attribution: {
    contributors: [{ name: 'Synthetic Fixture Author', role: 'curated_record' }],
  },
  links: [
    {
      rel: 'same_sample_as',
      target: GRAPH_LINK_TARGET,
      basis: 'shared_material_batch',
      notes: 'Synthetic fixture link.',
    },
  ],
};

export function graphArtifactsExported(
  state: 'current' | 'stale' = 'current',
): ApiArtifactsResponse {
  return {
    record: graphExportedRecord,
    sidecar: { record_id: GRAPH_RECORD_ID, schema_version: '1.05', evidence: {} },
    record_filename: `${GRAPH_RECORD_ID}.json`,
    sidecar_filename: `${GRAPH_RECORD_ID}.evidence.json`,
    artifact: { state, reason: state === 'stale' ? 'record changed after export' : null },
  };
}

/** The default (pre-export) bundle: the state a scientist is in most often. */
export function experimentGraphBundle(
  overrides: Partial<ExperimentGraphBundle> = {},
): ExperimentGraphBundle {
  return {
    detail: graphDetail(),
    groups: graphGroups,
    evidence: graphEvidence,
    artifacts: graphArtifactsNull,
    validate: graphValidateDryRun,
    warnings: graphWarnings,
    classification: graphClassification,
    ...overrides,
  };
}

/** The exported bundle: a real record id, real blocks, and ONE declared link. */
export function exportedExperimentGraphBundle(
  state: 'current' | 'stale' = 'current',
): ExperimentGraphBundle {
  return experimentGraphBundle({
    detail: graphDetail({
      exported: true,
      record_id: GRAPH_RECORD_ID,
      pending_count: 0,
      artifact: { state, reason: null },
      workflow: fixtureWorkflow({
        pending_count: 0,
        draft_ok: true,
        ready: true,
        exported: true,
        rev: VERSION.rev,
      }),
    }),
    artifacts: graphArtifactsExported(state),
    validate: { ok: true, errors: [], schema: 'ISAAC v1.05', dry_run: false },
    warnings: { advisory: true, gating: false, warnings: [] },
  });
}

/**
 * A LARGE but plausible experiment: one long spectral series with many channels,
 * many archived assets, and an evidence entry per field.
 *
 * Plausible is the operative word — a beamline campaign with 48 detector
 * channels and 60 archived files is a big experiment, not an impossible one.
 * The point of the fixture is that the surface must stay bounded and responsive
 * on it, and must SAY it is bounded rather than silently truncating.
 */
export function stressExperimentGraphBundle(opts?: {
  channels?: number;
  assets?: number;
  fields?: number;
}): ExperimentGraphBundle {
  const channelCount = opts?.channels ?? 48;
  const assetCount = opts?.assets ?? 60;
  const fieldCount = opts?.fields ?? 120;

  const fields = Array.from({ length: fieldCount }, (_, i) => ({
    path: `measurement.synthetic_parameter_${String(i).padStart(3, '0')}`,
    label: `Synthetic Parameter ${i}`,
    value: i,
    status: 'verified' as const,
    evidence_count: 1,
    source_types: ['spreadsheet' as const],
  }));

  const evidence: ApiEvidenceEntry[] = fields.map((f, i) => ({
    path: f.path,
    value: f.value,
    status: 'verified',
    evidence: [
      {
        source_type: 'spreadsheet',
        source_file: `mock_campaign_part_${i % 4}.csv`,
        locator: `row ${i + 2}`,
        quote: String(i),
      },
    ],
  }));

  for (let i = 0; i < assetCount; i += 1) {
    evidence.push({
      path: `assets:synthetic_asset_${String(i).padStart(3, '0')}`,
      value: `0000000000000000000000000000000000000000000000000000000000000${String(i).padStart(3, '0')}`,
      status: 'verified',
      evidence: [
        {
          source_type: 'file_listing',
          source_file: 'raw_scan_listing.txt',
          locator: `line ${i + 1}`,
          quote: `scan_${i}.h5`,
        },
      ],
    });
  }

  const record: Record<string, unknown> = {
    isaac_record_version: '1.05',
    record_id: GRAPH_RECORD_ID,
    measurement: {
      series: [
        {
          series_id: 'stress_spectrum',
          independent_variables: [{ name: 'incident_energy', unit: 'eV', values: [] }],
          channels: Array.from({ length: channelCount }, (_, i) => ({
            name: `channel_${String(i).padStart(2, '0')}`,
            unit: 'counts',
            role: i === 0 ? 'primary_signal' : 'auxiliary_signal',
            values: [],
          })),
        },
      ],
      qc: { status: 'valid' },
    },
    assets: Array.from({ length: assetCount }, (_, i) => ({
      asset_id: `synthetic_asset_${String(i).padStart(3, '0')}`,
      content_role: 'raw_data_pointer',
      media_type: 'application/x-hdf5',
    })),
    links: [],
  };

  return experimentGraphBundle({
    detail: graphDetail({
      exported: true,
      record_id: GRAPH_RECORD_ID,
      evidenced_field_count: fieldCount,
    }),
    groups: [{ title: 'Measurement', fields }],
    evidence,
    artifacts: {
      record,
      sidecar: { record_id: GRAPH_RECORD_ID, schema_version: '1.05', evidence: {} },
      record_filename: `${GRAPH_RECORD_ID}.json`,
      sidecar_filename: `${GRAPH_RECORD_ID}.evidence.json`,
      artifact: { state: 'current', reason: null },
    },
    validate: { ok: true, errors: [], schema: 'ISAAC v1.05', dry_run: false },
    warnings: { advisory: true, gating: false, warnings: [] },
    classification: { record_rev: 0, field_results: [], counts: graphClassification.counts },
  });
}

/** The seven routes the graph view fetches, for a component test. */
export function experimentGraphRoutes(
  id: string = GRAPH_EXP_ID,
  bundle: ExperimentGraphBundle = experimentGraphBundle(),
): Record<string, { body: unknown }> {
  const base = `/api/experiments/${encodeURIComponent(id)}`;
  return {
    [`GET ${base}`]: { body: { ...bundle.detail, id } },
    [`GET ${base}/draft`]: { body: { groups: bundle.groups } },
    [`GET ${base}/evidence`]: { body: { evidence: bundle.evidence } },
    [`GET ${base}/artifacts`]: { body: bundle.artifacts },
    [`POST ${base}/validate`]: { body: bundle.validate },
    [`GET ${base}/warnings`]: { body: bundle.warnings },
    [`GET ${base}/evidence-classification`]: { body: bundle.classification },
  };
}
