/*
 * BL15-2 LARGE-CORPUS REVIEW — `BL15R-012`.
 *
 * ── THE FIXTURE IS GENERATED BY THE REAL CONTRACT, NOT HAND-WRITTEN ────────
 *
 * `fixtures/bl15-corpus-review.json` was produced by calling
 * `bl15.relate.relate()`, `ArchiveInventory.to_state()`, `SourceEvidence.to_state()`
 * and `mapping.coverage()`/`MAPPINGS` in Python and serialising the result. So a
 * field this suite reads that the contract does not emit would have been absent
 * from the fixture and the test would have failed while being written — which is
 * the opposite of a hand-authored payload, where a typo'd key silently agrees with
 * the component that shares it. §1 asserts that property rather than trusting it.
 *
 * Its corpus deliberately reproduces the real archive's anomalies at 1/30 the
 * size: a THREE-reading `internal_declaration_vs_filename` conflict, a duplicated
 * legacy number, a macro target never acquired, a measurement with ZERO scans, two
 * units that are not run candidates, a `group_token: null` bucket, and beamtime
 * documentation attached to nothing. Every sample name is unmistakably fake (`ZZ1`,
 * `ZZOxide`) per `CLAUDE.md` §6.
 *
 *   §1  the fixture really is the contract's own shape
 *   §2  the digest, and every number derived rather than literal
 *   §3  no 1,192-row manifest, and the absence is stated
 *   §4  sample groups, including the `null` bucket
 *   §5  the measurements table, and `source_count` rather than `scans+1`
 *   §6  conflicts: THREE readings, the server's explanation, no winner
 *   §7  the mapping registry as five outcomes, never a progress bar
 *   §8  the ceiling — and no "Ready" anywhere
 *   §9  the evidence drawer, and the literal never replaced
 *   §10 search and filter over the real scale
 *   §11 what the import left out
 *
 * MUTATION-CHECKED: a test whose docstring carries a `MUTATION:` line was verified
 * by breaking the component in the way the test claims to catch, confirming it went
 * RED, and reverting. One without the line does not claim it.
 */

import { describe, it, expect } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { ImportCorpusReview } from '../components/ImportCorpusReview';
import {
  BL15_COPY,
  BL15_STATUS_LABELS,
} from '../lib/bl15ReviewContent';
import {
  BL15_MAPPING_STATUSES,
  cellFor,
  conflictsByKind,
  corpusDigest,
  readingsByStem,
  unattachedByType,
  unitState,
  type Bl15CorpusReview,
} from '../lib/bl15Review';

const REVIEW = JSON.parse(
  readFileSync(join(__dirname, 'fixtures', 'bl15-corpus-review.json'), 'utf8'),
) as Bl15CorpusReview;

const renderReview = (review: Bl15CorpusReview = REVIEW) =>
  render(<ImportCorpusReview review={review} />);

/* ── §1 · the fixture is the contract's own shape ────────────────────────── */

describe('BL15 review · §1 the fixture is the contract, not a hand-written guess', () => {
  it('carries exactly the keys MeasurementUnit.to_state() emits', () => {
    // The SAME key set `apps/api/tests/test_bl15_relate.py`'s
    // `test_nothing_in_the_output_carries_a_scientific_value` pins. If the Python
    // contract gains or loses a key, regenerating this fixture fails here — which
    // is what makes the whole suite a contract test rather than a mirror of itself.
    expect(Object.keys(REVIEW.relationships.units[0]).sort()).toEqual(
      [
        'acquisition_path',
        'conflicts',
        'declared_by',
        'duplicate_copies',
        'group_token',
        'internal_declaration',
        'legacy_number',
        'note_rows',
        'processed_products',
        'run_candidate',
        'scan_count',
        'scan_dir',
        'scans',
        'source_count',
        'source_type',
        'stem',
        'suppressed_duplicate_acquisitions',
      ].sort(),
    );
  });

  it('carries NO scientific value on any unit — they live only in evidence', () => {
    // The constraint that shapes the whole surface. A unit has no sample, medium,
    // state, filter or potential; those are joined from `SourceEvidence` by
    // `measurement_stem`. A future slice tempted to hang a parsed potential off a
    // unit should read that Python test's docstring first.
    for (const u of REVIEW.relationships.units) {
      const keys = Object.keys(u);
      for (const forbidden of [
        'sample',
        'sample_name',
        'medium',
        'electrolyte',
        'filter',
        'potential',
        'cycling_state',
      ]) {
        expect(keys).not.toContain(forbidden);
      }
    }
    // And the evidence really does carry them, so the join is not vacuous.
    const concepts = new Set(REVIEW.evidence.map((e) => e.concept));
    expect(concepts.has('sample_name')).toBe(true);
    expect(concepts.has('potential_magnitude')).toBe(true);
  });

  it('reproduces the real corpus anomalies the surface has to render', () => {
    const units = REVIEW.relationships.units;
    // a measurement with zero scans — legitimate; two real ones have none
    expect(units.some((u) => u.scan_count === 0)).toBe(true);
    // units that are NOT run candidates, with scans of their own
    const refs = units.filter((u) => !u.run_candidate);
    expect(refs.length).toBeGreaterThan(0);
    expect(refs.every((u) => u.scan_count > 0)).toBe(true);
    // a THREE-reading conflict
    const all = [
      ...units.flatMap((u) => u.conflicts),
      ...REVIEW.relationships.corpus_conflicts,
    ];
    expect(all.some((c) => c.readings.length >= 3)).toBe(true);
    // a duplicated legacy number
    expect(all.some((c) => c.kind === 'duplicate_legacy_number')).toBe(true);
    // a group with no token at all
    expect(REVIEW.relationships.groups.some((g) => g.group_token === null)).toBe(true);
  });
});

/* ── §2 · the digest ────────────────────────────────────────────────────── */

describe('BL15 review · §2 the digest is derived, never literal', () => {
  it('derives every count from the payload and says which expression', () => {
    const digest = corpusDigest(REVIEW);
    // Recomputed here INDEPENDENTLY of `corpusDigest` — a second expression of
    // each sum, so a bug in the first is not confirmed by reusing it.
    const units = REVIEW.relationships.units;
    const byId = new Map(digest.map((r) => [r.id, r.value]));
    expect(byId.get('sources')).toBe(REVIEW.inventory.entry_count);
    expect(byId.get('measurements')).toBe(REVIEW.relationships.unit_count);
    expect(byId.get('candidates')).toBe(units.filter((u) => u.run_candidate).length);
    expect(byId.get('reference')).toBe(units.filter((u) => !u.run_candidate).length);
    expect(byId.get('scans')).toBe(units.reduce((n, u) => n + u.scan_count, 0));
    expect(byId.get('macros')).toBe(
      new Set(units.flatMap((u) => u.declared_by.map((b) => b.macro_path))).size,
    );
    expect(byId.get('conflicts')).toBe(REVIEW.relationships.conflict_count);
    expect(byId.get('unattached')).toBe(REVIEW.relationships.unattached.length);
    // Every row states its provenance. A number with no expression beside it is
    // exactly the "shipped a count it had not derived" defect CLAUDE.md §11
    // records four times.
    for (const row of digest) expect(row.derivedFrom.length).toBeGreaterThan(0);
  });

  it('renders the digest as collapsed rows, each disclosing its expression', () => {
    const { container } = renderReview();
    const rows = container.querySelectorAll('details.bl15-digest-row');
    expect(rows.length).toBe(corpusDigest(REVIEW).length);
    rows.forEach((d) => expect((d as HTMLDetailsElement).open).toBe(false));
    // The expression is in the DOM even while shut — `querySelectorAll` reaches
    // inside a closed `<details>`, which is what lets a reader check the number.
    expect(container.textContent).toContain('relationships.unit_count');
    expect(container.textContent).toContain('inventory.entry_count');
  });

  it('MUTATION: a digest count that disagrees with the payload fails', () => {
    // MUTATION: `corpusDigest`'s `scans` row changed to `u.scans.length + 1`
    // summed — RUN, and it went RED on the `scans` assertion in the first test
    // of this section: `expected 22 to be 14`. (An earlier draft of this comment
    // guessed "15 against 23" from reasoning rather than from the run; the
    // measured pair is 14 against 22, and the guessed one is corrected here
    // rather than left standing as a number nobody produced.)
    const scans = REVIEW.relationships.units.reduce((n, u) => n + u.scan_count, 0);
    const wrong = REVIEW.relationships.units.reduce((n, u) => n + u.scans.length + 1, 0);
    expect(scans).not.toBe(wrong);
  });
});

/* ── §3 · no flat manifest ──────────────────────────────────────────────── */

describe('BL15 review · §3 the banned pattern, one layer down', () => {
  it('renders no row-per-source manifest and states that one is not available', () => {
    const { container } = renderReview();
    // `HIST-004` bans `Upload -> Spinner -> Mysterious JSON`; a 1,192-row table is
    // its sibling. Nothing here approaches the source count in rows.
    const rows = container.querySelectorAll('tbody tr');
    expect(rows.length).toBeLessThan(REVIEW.inventory.entry_count);
    // And the absence is STATED rather than implied by a missing link, because
    // `ArchiveInventory.to_state()` omits `entries` entirely.
    expect(
      screen.getByText(/complete file-by-file list is not part of this report/i),
    ).toBeInTheDocument();
  });

  it('never claims the manifest is one click away', () => {
    const { container } = renderReview();
    const text = (container.textContent ?? '').toLowerCase();
    expect(text).not.toContain('view all sources');
    expect(text).not.toContain('see the full manifest');
    expect(text).not.toContain('browse all files');
  });
});

/* ── §4 · sample groups ─────────────────────────────────────────────────── */

describe('BL15 review · §4 sample groups, including the bucket with no token', () => {
  it('names the null-token bucket in words rather than rendering an empty heading', () => {
    renderReview();
    // `relate._groups` emits `group_token: null` and sorts it last;
    // `test_a_stem_with_no_group_token_is_grouped_under_None_not_a_placeholder`
    // pins that it gets no placeholder. So the SURFACE has to supply the words.
    expect(screen.getByText('No sample token')).toBeInTheDocument();
    expect(screen.queryByText('Sample null')).not.toBeInTheDocument();
    expect(screen.queryByText(/^Sample $/)).not.toBeInTheDocument();
  });

  it('states contiguity as corroboration and a broken range as a warning', () => {
    const { container } = renderReview();
    const text = container.textContent ?? '';
    // The grouping is a CANDIDATE. `SampleGroup`'s docstring: "Corroboration is
    // not proof — a token meaning something else could produce contiguous ranges
    // too." The copy must not upgrade it.
    expect(text).toMatch(/corroboration for the grouping, not proof of it/i);
    expect(text).not.toMatch(/confirms the sample/i);
    expect(text).not.toMatch(/proves the grouping/i);
  });

  it('shows each group its own measurement count and legacy range', () => {
    renderReview();
    const g = REVIEW.relationships.groups.find((x) => x.group_token !== null)!;
    expect(screen.getByText(`Sample ${g.group_token}`)).toBeInTheDocument();
    expect(
      screen.getByText(
        new RegExp(`${g.measurement_count} measurements.*legacy ${g.legacy_low}`),
      ),
    ).toBeInTheDocument();
  });
});

/* ── §5 · the measurements table ────────────────────────────────────────── */

describe('BL15 review · §5 the table renders the server’s own counts', () => {
  it('renders source_count, NOT scans.length + 1', () => {
    // The instruction this exists for, and the numbers that make it checkable:
    // `MeasurementUnit.source_count` counts a byte-identical copy ONCE, and on
    // this fixture a unit with 3 scans has 7 sources (acquisition + 3 scans +
    // 1 macro + 1 processed product + 1 note row) where `scans+1` gives 4.
    const unit = REVIEW.relationships.units.find((u) => u.source_count > u.scans.length + 1)!;
    expect(unit).toBeDefined();
    const { container } = renderReview();
    const row = [...container.querySelectorAll('tbody tr.bl15-row')].find((tr) =>
      (tr.textContent ?? '').includes(unit.stem),
    )!;
    const nums = [...row.querySelectorAll('td.bl15-num')].map((td) => td.textContent);
    expect(nums).toEqual([String(unit.scan_count), String(unit.source_count)]);
    expect(nums).not.toContain(String(unit.scans.length + 1));
  });

  it('renders a zero-scan measurement rather than hiding or flagging it', () => {
    const zero = REVIEW.relationships.units.find((u) => u.scan_count === 0)!;
    const { container } = renderReview();
    const row = [...container.querySelectorAll('tbody tr.bl15-row')].find((tr) =>
      (tr.textContent ?? '').includes(zero.stem),
    );
    // Zero is legitimate — `scan_count`'s docstring says two real measurements
    // have none — so it must not read as an error.
    expect(row).toBeDefined();
    expect(row!.className).not.toMatch(/error|invalid|fail/);
  });

  it('never offers alignment or a standard as a Run', () => {
    const ref = REVIEW.relationships.units.find((u) => !u.run_candidate)!;
    const { container } = renderReview();
    const row = [...container.querySelectorAll('tbody tr.bl15-row')].find((tr) =>
      (tr.textContent ?? '').includes(ref.stem),
    )!;
    // Its own category, stated. `RUN_CANDIDATE_SOURCE_TYPES` is exactly
    // `{spec_acquisition}`, and excluding these units entirely would orphan
    // 242 of 908 real scans — so they are shown, and shown as what they are.
    expect(row.textContent).toContain('Alignment or standard');
    expect(row.className).toContain('bl15-row-reference');
  });

  it('says "not stated" rather than leaving a cell blank', () => {
    const { container } = renderReview();
    // A blank cell is indistinguishable from a rendering failure. `cellFor`'s
    // `absent` state is a real outcome and renders a word.
    expect(container.querySelectorAll('.bl15-absent').length).toBeGreaterThan(0);
  });

  it('marks a cell disputed only when the literals actually differ', () => {
    // Two sources stating the same thing CORROBORATE. Calling that a dispute
    // would put a warning on the best-evidenced values in the corpus.
    const same = new Map([
      ['filter', [{ raw_literal: '35' }, { raw_literal: '35' }]],
    ]) as never;
    expect(cellFor(same, 'filter').state).toBe('read');
    const differ = new Map([
      ['filter', [{ raw_literal: '35' }, { raw_literal: '10' }]],
    ]) as never;
    expect(cellFor(differ, 'filter').state).toBe('disputed');
  });
});

/* ── §6 · conflicts ─────────────────────────────────────────────────────── */

describe('BL15 review · §6 conflicts are unmissable and never adjudicated', () => {
  it('renders ALL THREE readings of the three-source disagreement', () => {
    const three = [
      ...REVIEW.relationships.units.flatMap((u) => u.conflicts),
      ...REVIEW.relationships.corpus_conflicts,
    ].find((c) => c.readings.length >= 3)!;
    expect(three).toBeDefined();
    const { container } = renderReview();
    /*
     * SELECTED BY KIND, NOT BY SUBJECT — and the first version of this test was
     * wrong in a way worth recording. `.find()` on subject matched the FIRST
     * `.bl15-conflict` mentioning the stem, and this fixture's three-way
     * `internal_declaration_vs_filename` shares its stem with a two-reading
     * `acquired_never_declared`. So the assertion read 2 against 3 and looked
     * like a component defect when the component was right.
     */
    const kindBlock = [...container.querySelectorAll('.bl15-conflict-kind')].find((el) =>
      (el.querySelector('.bl15-conflict-kind-title')?.textContent ?? '').includes(
        'header disagrees with its name',
      ),
    )!;
    expect(kindBlock).toBeDefined();
    const block = [...kindBlock.querySelectorAll('.bl15-conflict')].find((el) =>
      (el.textContent ?? '').includes(three.subject),
    )!;
    // A surface built for exactly two would be wrong about the corpus's most
    // instructive case — `Conflict`'s own docstring says so.
    const readings = block.querySelectorAll('.bl15-readings > li');
    expect(readings.length).toBe(three.readings.length);
    for (const r of three.readings) {
      expect(block.textContent).toContain(r.value);
      expect(block.textContent).toContain(r.source_path);
      expect(block.textContent).toContain(r.locator);
    }
  });

  it('renders the server’s explanation verbatim and writes none of its own', () => {
    const { container } = renderReview();
    const all = [
      ...REVIEW.relationships.units.flatMap((u) => u.conflicts),
      ...REVIEW.relationships.corpus_conflicts,
    ];
    // `Conflict.explanation` is REQUIRED at construction and is written for a
    // scientist by `bl15/relate.py`. Rendering a paraphrase would be a second
    // vocabulary free to drift from the one that enforces the conflict.
    for (const c of all) {
      expect(container.textContent).toContain(c.explanation);
    }
  });

  it('shows no chosen winner and states that nothing was resolved', () => {
    const { container } = renderReview();
    const text = (container.textContent ?? '').toLowerCase();
    expect(text).toContain('no source is preferred here');
    expect(text).not.toContain('most likely');
    expect(text).not.toContain('best match');
    expect(text).not.toContain('recommended value');
    expect(text).not.toContain('we chose');
    // `unresolved_reason` is always `sources_disagree` and is surfaced as such.
    expect(container.textContent).toContain('sources_disagree');
  });

  it('groups conflicts by kind and counts each group', () => {
    const groups = conflictsByKind(REVIEW.relationships);
    expect(groups.length).toBeGreaterThan(1);
    renderReview();
    // A scientist-readable name per kind; the EXPLANATION still comes from the
    // server, so these labels make no claim the payload is not also making.
    expect(screen.getByText(/The file’s own header disagrees with its name/)).toBeInTheDocument();
    expect(screen.getByText(/Two files claim the same legacy number/)).toBeInTheDocument();
  });

  it('MUTATION: rendering only the first two readings fails', () => {
    // MUTATION: `ConflictView` changed to `conflict.readings.slice(0, 2).map(...)`
    // — went RED on the three-readings test above (3 expected, 2 rendered).
    const three = [
      ...REVIEW.relationships.units.flatMap((u) => u.conflicts),
      ...REVIEW.relationships.corpus_conflicts,
    ].find((c) => c.readings.length >= 3)!;
    expect(three.readings.slice(0, 2).length).not.toBe(three.readings.length);
  });
});

/* ── §7 · mapping review ────────────────────────────────────────────────── */

describe('BL15 review · §7 five outcomes, never a progress bar', () => {
  it('renders all five statuses with the registry’s own counts', () => {
    renderReview();
    const cov = REVIEW.mapping.coverage;
    /*
     * ── THESE NUMBERS MOVED ON 2026-09-17, AND THE MOVE WAS A CORRECTION OF THIS
     *    FIXTURE RATHER THAN A CHANGE TO THE REGISTRY ───────────────────────────
     *
     * They read `2 + 4 + 14 + 24 + 1` and now read `1 + 4 + 15 + 24 + 1`. Nothing
     * in `bl15/mapping.py` was touched by the change that updated them: the
     * fixture was frozen at `b6f23e6a` and the registry moved afterwards in
     * `57e06392` (a technique mapping that proposed a macro filename as the
     * schema technique), `682d41ce` and `ad0d2596` — so `acquisition_method` left
     * `deterministic` for `needs_domain_review` and this file has been asserting
     * against a registry state the server no longer has.
     *
     * The fixture was refreshed from `historical_import._mapping_block()`
     * VERBATIM, which is also what added `placement_level`, `placement_name`,
     * `domain_questions` and `unresolved_questions` to every concept and the
     * placement/question members to the block. `§1`'s premise is that this
     * fixture IS the contract's shape; a stale one is worse than no fixture,
     * because a green suite over it reads as agreement.
     *
     * The total is unchanged at 45 and is the one number a status move cannot
     * touch, which is why it is asserted separately below.
     */
    expect(cov.deterministic + cov.normalized).toBe(5);
    expect(cov.needs_domain_review).toBe(15);
    expect(cov.not_expressible).toBe(24);
    expect(cov.blocked_by_build).toBe(1);
    expect(cov.concepts_total).toBe(45);
    expect(
      cov.deterministic +
        cov.normalized +
        cov.needs_domain_review +
        cov.not_expressible +
        cov.blocked_by_build,
    ).toBe(cov.concepts_total);
    for (const label of [
      'Taken as written',
      'Carried across by a named rule',
      'Needs a domain owner to choose',
      'The schema has no field for it',
      'The schema has a field this build cannot reach',
    ]) {
      expect(screen.getByText(label)).toBeInTheDocument();
    }
  });

  it('renders NO progress bar and no completion percentage over mapping', () => {
    const { container } = renderReview();
    // 5 of 45 proposable would read as 89% failure, when 24 of those are a
    // correct description of the official schema's coverage and 14 are a
    // question for a domain owner. So there is no bar and no percentage.
    expect(container.querySelector('progress')).toBeNull();
    expect(container.querySelector('[role="progressbar"]')).toBeNull();
    const text = container.textContent ?? '';
    expect(text).not.toMatch(/\d+%/);
    expect(text).not.toMatch(/fields mapped/i);
    /*
     * BOUNDED, because the first version was not. `/\bcomplete\b.*\d+ of 45/i`
     * ran `.*` across the ENTIRE rendered document, so the word "complete"
     * anywhere plus any later "N of 45" matched — and both occur legitimately.
     * A regex that can match across unrelated paragraphs is not a measurement of
     * anything. Bounded to a short window, it says what it means.
     */
    expect(text).not.toMatch(/\d+ of 45 (concepts )?(are )?(complete|mapped|done)/i);
    expect(text).not.toMatch(/(complete|mapped|done)[^.]{0,20}\d+ of 45/i);
  });

  it('renders each concept’s own reason verbatim', () => {
    const { container } = renderReview();
    // `ConceptMapping.reason` is "WHY this status — in a sentence a scientist
    // reads, not a code". All five statuses are first-class outcomes, so every
    // reason is rendered, not only the ones that carry a value.
    for (const c of REVIEW.mapping.concepts) {
      expect(container.textContent).toContain(c.reason);
    }
  });

  it('renders every concept’s DEC-41 placement, words and level', () => {
    const { container } = renderReview();
    const text = container.textContent ?? '';
    /*
     * A PLACEMENT IS NOT A STATUS, and that is the reason this is rendered at all.
     * `status` says whether a value may TRAVEL toward a candidate; a placement says
     * whether the information has a HOME. Without it a scientist reading "The schema
     * has no field for it" over 24 concepts has no way to tell "this is discarded"
     * from "this is kept, in the Extended Context companion" — and the second is
     * what `DEC-41` actually decided for all twelve of the level-4 ones.
     */
    for (const c of REVIEW.mapping.concepts) {
      expect(c.placement_level).toBeGreaterThanOrEqual(1);
      expect(c.placement_level).toBeLessThanOrEqual(4);
      expect(typeof c.placement_name).toBe('string');
      // THE SERVER'S OWN WORDS, verbatim — no label is re-authored in the client.
      expect(text).toContain(c.placement_name as string);
    }
    // ALL FOUR LEVELS ARE REPRESENTED by this registry, so the assertion above is
    // not passing on one repeated value.
    const levels = new Set(REVIEW.mapping.concepts.map((c) => c.placement_level));
    expect([...levels].sort()).toEqual([1, 2, 3, 4]);
    expect(text).toMatch(/structured ISAAC Extended Context companion/);
  });

  it('shows only the OPEN domain questions, never the closed ones', () => {
    const { container } = renderReview();
    const text = container.textContent ?? '';
    /*
     * Twelve of the twenty packet questions closed on 2026-09-17. A surface reading
     * `domain_questions` rather than `unresolved_questions` would keep telling a
     * scientist to wait for an answer that has already arrived — the defect
     * `CTX-001` names, and the reason the server publishes both lists.
     */
    const open = new Set(REVIEW.mapping.open_domain_questions ?? []);
    expect(open.size).toBeGreaterThan(0);
    const closed = (REVIEW.mapping.domain_questions ?? [])
      .filter((q) => !q.is_open)
      .map((q) => q.question_id);
    expect(closed.length).toBeGreaterThan(0);

    /*
     * QUERIED BY CLASS, NOT REGEXED OUT OF THE PAGE PROSE — and the previous version
     * of this assertion is why.
     *
     * It read `text.matchAll(/Still waiting on a domain answer: ([^.]+)\./g)` and then
     * split the capture on `,\s*` to recover bare ids. That worked only while the line
     * rendered `Q6` and nothing else. It breaks on the humanized line two ways at once:
     * the separator is now `; `, and `[^.]+` truncates at the FIRST dot — so `Q14`,
     * whose subject is "is measurement.qc.status derivable from the notes?", would have
     * been cut mid-path. A prose regex was load-bearing on copy that was always going
     * to change.
     *
     * Reading `.bl15-concept-open` and pulling the id out of its parenthetical is
     * stable under any rewording, and it lets the assertion get STRONGER rather than
     * merely survive: the subject must be present, which is the guard that stops this
     * line ever regressing to a bare internal number.
     */
    const byId = new Map((REVIEW.mapping.domain_questions ?? []).map((q) => [q.question_id, q]));
    const lines = [...container.querySelectorAll('.bl15-concept-open')];
    expect(lines.length).toBeGreaterThan(0);
    for (const el of lines) {
      const line = el.textContent ?? '';
      const ids = [...line.matchAll(/\(([A-Z]\d+)\)/g)].map((m) => m[1]);
      expect(ids.length).toBeGreaterThan(0);
      for (const id of ids) {
        expect(open.has(id)).toBe(true);
        expect(closed).not.toContain(id);
        // THE HUMANIZATION GUARD. `CLAUDE.md` §11 records this defect class at length
        // and closed it on 2026-09-14 for blocker keys: an internal identifier
        // rendered to a scientist beside an already-correct human label. `Q6` is a
        // packet number with no meaning outside this repository's own documents, and
        // the server already ships the text — so a line that shows the id ALONE is a
        // defect, not a style choice.
        const subject = byId.get(id)?.subject ?? '';
        expect(subject.length).toBeGreaterThan(0);
        expect(line).toContain(subject);
      }
    }
    // And the id is KEPT, not replaced: it is the traceable handle into
    // `docs/bl15-2-domain-questions-2026-09-16.md`.
    expect(text).toMatch(/\([A-Z]\d+\)/);
  });

  it('renders no Python module path and no field:/block: address as a schema path', () => {
    const { container } = renderReview();
    const text = container.textContent ?? '';
    /*
     * `CLAUDE.md` §11's measured rule: a Python module path rendered to a scientist
     * as though it were an official-schema path is a defect with a history here
     * (`serialize.draft_to_groups` rendered eight times on one screen), and so is a
     * `field:`/`block:` internal address. The placement lines added above are plain
     * English by construction — they render `placement_name`, which is the
     * registry's own words — and this asserts it rather than trusting it.
     */
    expect(text).not.toMatch(/\bfield:[a-z]/);
    expect(text).not.toMatch(/\bblock:[a-z]/);
    expect(text).not.toMatch(/\b[a-z_]+\.py\b/);
    expect(text).not.toMatch(/\b(mapping|evidence|serialize|reconstruct)\.[a-z_]+\(/);
  });

  it('shows a normalized value beside its raw literal with the rule', () => {
    const { container } = renderReview();
    // `ffilter35` is the case this exists for: the literal survives, "35" sits
    // next to it, and the rule that produced it is named.
    expect(container.textContent).toContain('ffilter35');
    expect(container.textContent).toContain('doubled_prefix_ffilter');
    expect(container.textContent).toMatch(/as written/);
  });
});

/* ── §8 · the ceiling ───────────────────────────────────────────────────── */

describe('BL15 review · §8 what cannot be finished, said rather than discovered', () => {
  it('renders all three blockers using the registry’s own sentences', () => {
    const { container } = renderReview();
    expect(container.textContent).toContain(REVIEW.mapping.temperature_absent_reason);
    expect(container.textContent).toContain(REVIEW.mapping.assets_blocked_reason);
    expect(container.textContent).toMatch(/requires\s+descriptors/i);
  });

  it('never defaults a temperature and never claims export-readiness', () => {
    const { container } = renderReview();
    const text = container.textContent ?? '';
    /*
     * "298" IS PRESENT AND MUST BE — and asserting its absence was my own error,
     * caught by this test failing. It occurs exactly once in the payload, inside
     * `TEMPERATURE_ABSENT_REASON` itself: *"298 must not be defaulted into
     * context.temperature_K, because a plausible number in a required field is a
     * fabricated measurement."* Requirement 6 is to render that sentence, so a
     * blanket ban on the digits contradicts the thing it was trying to protect.
     *
     * What is actually checkable is that the number never appears as a VALUE —
     * never in a table cell, and never in the evidence drawer.
     */
    expect(REVIEW.mapping.temperature_absent_reason).toContain('298');
    const cells = [...container.querySelectorAll('td'), ...container.querySelectorAll('.bl15-evidence-sources li')];
    for (const cell of cells) expect(cell.textContent ?? '').not.toContain('298');
    expect(text).not.toMatch(/ready to export/i);
    expect(text).not.toMatch(/export-ready/i);
  });

  it('has NO state, label or filter called Ready', () => {
    const { container } = renderReview();
    // The integration design §5: a candidate Run from this corpus cannot be
    // export-ready. A bucket named "Ready" would be read as a promise the build
    // cannot keep, so the states name what was OBSERVED instead.
    const text = container.textContent ?? '';
    expect(text).not.toMatch(/\bReady\b/);
    expect(unitState(REVIEW.relationships.units[0], undefined)).not.toBe('ready');
    for (const u of REVIEW.relationships.units) {
      expect(['reference', 'conflict', 'no_values', 'values_read']).toContain(
        unitState(u, readingsByStem(REVIEW.evidence).get(u.stem)),
      );
    }
  });
});

/* ── §9 · the evidence drawer ───────────────────────────────────────────── */

describe('BL15 review · §9 the evidence drawer is scientist-readable', () => {
  it('shows filename + what it says for each supporting source', () => {
    const { container } = renderReview();
    const index = readingsByStem(REVIEW.evidence);
    const stem = [...index.keys()][0];
    const drawer = [...container.querySelectorAll('.bl15-evidence')].find((el) =>
      (el.textContent ?? '').length > 0,
    )!;
    expect(drawer).toBeDefined();
    const hit = REVIEW.evidence.find((e) => e.measurement_stem === stem)!;
    // The scientist's own handle on the source is the filename, never an opaque
    // id — `SourceEvidence.source_path`'s docstring says exactly that.
    expect(container.textContent).toContain(hit.source_path);
    expect(container.textContent).toContain(hit.raw_literal);
    expect(container.textContent).toContain(hit.locator);
  });

  it('renders no raw JSON anywhere', () => {
    const { container } = renderReview();
    const text = container.textContent ?? '';
    // `HIST-004`'s third banned half. A payload dump would satisfy "shows the
    // evidence" while being unreadable.
    expect(text).not.toContain('{"');
    expect(text).not.toContain('evidence_id');
    expect(text).not.toContain('"raw_literal"');
    expect(text).not.toContain('parser_id');
  });

  it('never replaces the raw literal with the normalized value', () => {
    const { container } = renderReview();
    const normalised = REVIEW.evidence.filter(
      (e) => e.normalized_value !== null && e.normalized_value !== undefined,
    );
    expect(normalised.length).toBeGreaterThan(0);
    // "Rewriting the source would destroy the only thing that lets a scientist
    // disagree." Both are present, for every normalised statement.
    for (const e of normalised) {
      expect(container.textContent).toContain(e.raw_literal);
    }
  });

  it('states the source count with its own caveat, not as a bare number', () => {
    const { container } = renderReview();
    expect(container.textContent).toMatch(
      /distinct sources? support this measurement, counting byte-identical copies once/i,
    );
  });
});

/* ── §10 · search and filter ────────────────────────────────────────────── */

describe('BL15 review · §10 search and filter over the real scale', () => {
  it('filters to conflicts only, and the count follows', () => {
    const { container } = renderReview();
    const before = container.querySelectorAll('tbody tr.bl15-row').length;
    fireEvent.click(screen.getByRole('radio', { name: 'Sources disagree' }));
    const after = [...container.querySelectorAll('tbody tr.bl15-row')];
    expect(after.length).toBeLessThan(before);
    expect(after.length).toBeGreaterThan(0);
    for (const row of after) expect(row.className).toContain('bl15-row-conflict');
  });

  it('separates alignment and standards into their own category', () => {
    const { container } = renderReview();
    fireEvent.click(screen.getByRole('radio', { name: 'Alignment or standard' }));
    const rows = [...container.querySelectorAll('tbody tr.bl15-row')];
    expect(rows.length).toBe(REVIEW.relationships.units.filter((u) => !u.run_candidate).length);
    for (const row of rows) expect(row.className).toContain('bl15-row-reference');
  });

  it('searches by legacy number, stem and read value', () => {
    const { container } = renderReview();
    const box = screen.getByRole('searchbox', { name: /search measurements/i });
    fireEvent.change(box, { target: { value: 'ZZ2' } });
    let rows = [...container.querySelectorAll('tbody tr.bl15-row')];
    expect(rows.length).toBeGreaterThan(0);
    for (const r of rows) expect(r.textContent).toContain('ZZ2');
    // a value only the EVIDENCE carries, so this proves the join is searched too
    fireEvent.change(box, { target: { value: 'ffilter35' } });
    rows = [...container.querySelectorAll('tbody tr.bl15-row')];
    expect(rows.length).toBe(1);
  });

  it('says so when nothing matches instead of rendering an empty table', () => {
    const { container } = renderReview();
    fireEvent.change(screen.getByRole('searchbox', { name: /search measurements/i }), {
      target: { value: 'zzzz-no-such-measurement' },
    });
    expect(screen.getByText(/No measurement in this import matches/i)).toBeInTheDocument();
    expect(container.querySelectorAll('tbody tr.bl15-row').length).toBe(0);
  });
});

/* ── §11 · what was left out ────────────────────────────────────────────── */

describe('BL15 review · §11 what the import left out is as visible as what it kept', () => {
  it('lists every unattached source with the server’s own reason', () => {
    const { container } = renderReview();
    const groups = unattachedByType(REVIEW.relationships);
    expect(groups.length).toBeGreaterThan(0);
    // `Relationships.unattached` is "as load-bearing as `units`": a
    // reconstruction reporting only what it assembled leaves a scientist unable
    // to see what it left out.
    for (const g of groups) {
      expect(container.textContent).toContain(g.reason);
      for (const p of g.paths) expect(container.textContent).toContain(p);
    }
  });

  it('lists every refused entry with its measured value and the ceiling', () => {
    const { container } = renderReview();
    for (const r of REVIEW.inventory.refused) {
      expect(container.textContent).toContain(r.archive_path);
      expect(container.textContent).toContain(r.reason);
      if (r.detail) expect(container.textContent).toContain(r.detail);
    }
  });

  it('warns that a truncated walk makes every count a floor', () => {
    const truncated: Bl15CorpusReview = {
      ...REVIEW,
      inventory: { ...REVIEW.inventory, truncated_reason: 'too_many_entries' },
    };
    renderReview(truncated);
    // Stated BEFORE the digest, because it changes how every number in it reads.
    expect(
      screen.getByText(/stopped early \(too_many_entries\), so every\s+count below/i),
    ).toBeInTheDocument();
  });

  it('says nothing about truncation when the walk completed', () => {
    const { container } = renderReview();
    expect(container.querySelector('.bl15-warn')).toBeNull();
  });
});

/* ── §12 · disclosure discipline ────────────────────────────────────────── */

describe('BL15 review · §12 every summary is a topic, never a claim', () => {
  /*
   * WHAT THIS TEST CHECKS, AND WHY IT IS NOT A VERB BLACKLIST.
   *
   * The first version banned `is|are|was|were|has|have|cannot|will` from every
   * `<summary>`. It failed on this component's own `What Cannot Be Finished Here`
   * — and the failure was the test's fault, not the heading's. A verb blacklist
   * is a crude proxy for the real rule, and it mislabels a question-shaped
   * heading as an assertion.
   *
   * THE REAL HAZARD IS SPECIFIC: a server sentence that CARRIES SCOPE —
   * `ConceptMapping.reason`, `Conflict.explanation`, an `unattached[].reason`, or
   * one of the two ceiling reasons — being promoted into a summary, where
   * shutting the drawer leaves the claim standing without the qualification that
   * followed it. That is exactly the defect `SettingsPage`'s `PrivacyBody` guards
   * against with `no-telemetry`.
   *
   * So this asserts two things instead, both mechanical: every summary's text is
   * drawn from a CLOSED SET this component authors (stated as a set difference,
   * so an entirely new summary also fails), and no summary contains any
   * scope-carrying sentence from the payload.
   */
  it('draws every summary from a closed set of this component’s own labels', () => {
    const { container } = renderReview();
    const allowed = new Set<string>([
      ...corpusDigest(REVIEW).map((r) => `${r.value.toLocaleString('en-US')}${r.label}`),
      ...Object.values(BL15_STATUS_LABELS).map(
        (l) => `${l}${REVIEW.mapping.coverage[
          BL15_MAPPING_STATUSES.find((s) => BL15_STATUS_LABELS[s] === l)!
        ]} of ${REVIEW.mapping.coverage.concepts_total}`,
      ),
      BL15_COPY.ceilingTitle,
      BL15_COPY.leftOutTitle,
      ...REVIEW.relationships.units.map((u) => u.stem),
    ]);
    const seen = [...container.querySelectorAll('summary')].map((s) =>
      (s.textContent ?? '').replace(/\s+/g, ' ').trim(),
    );
    expect(seen.length).toBeGreaterThan(0);
    const norm = (t: string) => t.replace(/\s+/g, ' ').trim();
    const allowedNorm = new Set([...allowed].map(norm));
    expect(seen.filter((t) => !allowedNorm.has(t))).toEqual([]);
  });

  it('never promotes a scope-carrying server sentence into a summary', () => {
    const { container } = renderReview();
    const summaries = [...container.querySelectorAll('summary')].map((s) => s.textContent ?? '');
    const scopeCarrying = [
      ...REVIEW.mapping.concepts.map((c) => c.reason),
      ...REVIEW.relationships.units.flatMap((u) => u.conflicts.map((c) => c.explanation)),
      ...REVIEW.relationships.corpus_conflicts.map((c) => c.explanation),
      ...REVIEW.relationships.unattached.map((u) => u.reason),
      REVIEW.mapping.temperature_absent_reason,
      REVIEW.mapping.assets_blocked_reason,
    ];
    for (const sentence of scopeCarrying) {
      for (const summary of summaries) expect(summary).not.toContain(sentence);
    }
  });

  it('keeps every conflict explanation OUTSIDE a collapsed disclosure', () => {
    const { container } = renderReview();
    // A conflict a reader cannot see is a conflict they will not act on, and the
    // brief's requirement is that conflicts are unmissable. So the explanations
    // are not behind a shut drawer, unlike the digest expressions.
    const shut = [...container.querySelectorAll('details')].filter(
      (d) => !(d as HTMLDetailsElement).open,
    );
    const hidden = shut.map((d) => d.textContent ?? '').join(' ');
    for (const c of REVIEW.relationships.units.flatMap((u) => u.conflicts)) {
      expect(hidden).not.toContain(c.explanation);
    }
  });
});
